import 'package:flutter/material.dart';
import 'package:hapi/event/et.dart';
import 'package:hapi/main_c.dart';
import 'package:hapi/relic/relic.dart';
import 'package:hapi/tarikh/timeline/timeline_data.dart';

/// Asma Ul-Husna - The Most Beautiful Names, the 99 names of Allah.
class AsmaUlHusna extends Relic {
  AsmaUlHusna(Enum e)
      : super(
          // Event data:
          et: ET.Asma_ul__Husna,
          tkEra: ET.Asma_ul__Husna.tkIsimA,
          tkTitle: e.tkIsimA,
          start: 0,
          end: 0,
          // Relic data:
          e: e,
        );

  @override
  Asset getAsset({width = 200.0, height = 200.0, scale = 1.0}) => Asset(
        filename: 'images/Allah/asma_ul__husna/'
            '${e.index < 9 ? '0${e.index + 1}' : e.index + 1}_${e.name}.svg',
        width: width,
        height: height,
        scale: scale,
      );

  @override
  // TODO: implement widget
  Widget get widget => throw UnimplementedError();

  static List<Relic> get relics => _relics;
  static List<RelicSetFilter> get relicSetFilters => _relicSetFilters;
}

final List<Relic> _relics = [
  AsmaUlHusna(AUH.Ar__Rahman),
  AsmaUlHusna(AUH.Ar__Rahim),
  AsmaUlHusna(AUH.Al__Malik),
  AsmaUlHusna(AUH.Al__Quddus),
  AsmaUlHusna(AUH.As__Salam),
  AsmaUlHusna(AUH.Al__Mu_a_min),
  AsmaUlHusna(AUH.Al__Muhaymin),
  AsmaUlHusna(AUH.Al__Aziz),
  AsmaUlHusna(AUH.Al__Jabbar),
  AsmaUlHusna(AUH.Al__Mutakabbir),
  AsmaUlHusna(AUH.Al__Khaliq),
  AsmaUlHusna(AUH.Al__Bari_a_),
  AsmaUlHusna(AUH.Al__Musawwir),
  AsmaUlHusna(AUH.Al__Ghaffar),
  AsmaUlHusna(AUH.Al__Qahhar),
  AsmaUlHusna(AUH.Al__Wahhab),
  AsmaUlHusna(AUH.Ar__Razzaq),
  AsmaUlHusna(AUH.Al__Fattah),
  AsmaUlHusna(AUH.Al___a_Alim),
  AsmaUlHusna(AUH.Al__Qabid),
  AsmaUlHusna(AUH.Al__Basit),
  AsmaUlHusna(AUH.Al__Khafidh),
  AsmaUlHusna(AUH.Ar__Rafi_a_),
  AsmaUlHusna(AUH.Al__Mu_a_izz),
  AsmaUlHusna(AUH.Al__Muzill),
  AsmaUlHusna(AUH.As__Sami_a_),
  AsmaUlHusna(AUH.Al__Basir),
  AsmaUlHusna(AUH.Al__Hakam),
  AsmaUlHusna(AUH.Al___a_Adl),
  AsmaUlHusna(AUH.Al__Latif),
  AsmaUlHusna(AUH.Al__Khabir),
  AsmaUlHusna(AUH.Al__Halim),
  AsmaUlHusna(AUH.Al___a_Athim),
  AsmaUlHusna(AUH.Al__Ghafur),
  AsmaUlHusna(AUH.Ash__Shakur),
  AsmaUlHusna(AUH.Al___a_Ali),
  AsmaUlHusna(AUH.Al__Kabir),
  AsmaUlHusna(AUH.Al__Hafiz),
  AsmaUlHusna(AUH.Al__Muqit),
  AsmaUlHusna(AUH.Al__Hasib),
  AsmaUlHusna(AUH.Al__Jalil),
  AsmaUlHusna(AUH.Al__Karim),
  AsmaUlHusna(AUH.Ar__Raqib),
  AsmaUlHusna(AUH.Al__Mujib),
  AsmaUlHusna(AUH.Al__Wasi_a_),
  AsmaUlHusna(AUH.Al__Hakim),
  AsmaUlHusna(AUH.Al__Wadud),
  AsmaUlHusna(AUH.Al__Majid),
  AsmaUlHusna(AUH.Al__Ba_a_ith),
  AsmaUlHusna(AUH.Ash__Shahid),
  AsmaUlHusna(AUH.Al__Haqq),
  AsmaUlHusna(AUH.Al__Wakil),
  AsmaUlHusna(AUH.Al__Qawi),
  AsmaUlHusna(AUH.Al__Matin),
  AsmaUlHusna(AUH.Al__Wali),
  AsmaUlHusna(AUH.Al__Hamid),
  AsmaUlHusna(AUH.Al__Muhsi),
  AsmaUlHusna(AUH.Al__Mubdi),
  AsmaUlHusna(AUH.Al__Mu_a_id),
  AsmaUlHusna(AUH.Al__Muhyi),
  AsmaUlHusna(AUH.Al__Mumit),
  AsmaUlHusna(AUH.Al__Hayy),
  AsmaUlHusna(AUH.Al__Qayyum),
  AsmaUlHusna(AUH.Al__Wajid),
  AsmaUlHusna(AUH.Al__Maajid),
  AsmaUlHusna(AUH.Al__Wahid),
  AsmaUlHusna(AUH.Al__Ahad),
  AsmaUlHusna(AUH.As__Samad),
  AsmaUlHusna(AUH.Al__Qadir),
  AsmaUlHusna(AUH.Al__Muqtadir),
  AsmaUlHusna(AUH.Al__Muqaddim),
  AsmaUlHusna(AUH.Al__Mu_a_akhkhir),
  AsmaUlHusna(AUH.Al__Awwal),
  AsmaUlHusna(AUH.Al__Akhir),
  AsmaUlHusna(AUH.Az__Zahir),
  AsmaUlHusna(AUH.Al__Batin),
  AsmaUlHusna(AUH.Al__Waali),
  AsmaUlHusna(AUH.Al__Muta_a_ali),
  AsmaUlHusna(AUH.Al__Barr),
  AsmaUlHusna(AUH.At__Tawwab),
  AsmaUlHusna(AUH.Al__Muntaqim),
  AsmaUlHusna(AUH.Al___a_Afu),
  AsmaUlHusna(AUH.Ar__Ra_a_uf),
  AsmaUlHusna(AUH.Malik_ul__Mulk),
  AsmaUlHusna(AUH.Dhul__Jalali_Wal__Ikram),
  AsmaUlHusna(AUH.Al__Muqsit),
  AsmaUlHusna(AUH.Al__Jami_a_),
  AsmaUlHusna(AUH.Al__Ghani),
  AsmaUlHusna(AUH.Al__Mughni),
  AsmaUlHusna(AUH.Al__Mani_a_),
  AsmaUlHusna(AUH.Ad__Dharr),
  AsmaUlHusna(AUH.An__Nafi_a_),
  AsmaUlHusna(AUH.An__Nur),
  AsmaUlHusna(AUH.Al__Hadi),
  AsmaUlHusna(AUH.Al__Badi_a_),
  AsmaUlHusna(AUH.Al__Baqi),
  AsmaUlHusna(AUH.Al__Warith),
  AsmaUlHusna(AUH.Ar__Rashid),
  AsmaUlHusna(AUH.As__Sabur),
];

final List<RelicSetFilter> _relicSetFilters = [
  RelicSetFilter(
    tkLabel: 'a.Nabi',
    idxList: List.generate(
      _relics.length,
      (index) => _relics[index].e.index,
    ),
    tprMax: _relics.length,
  ),
  RelicSetFilter(
    tkLabel: 'a.Rasul',
    idxList: [
      AUH.Al__Ba_a_ith.index,
    ],
    tprMax: _relics.length,
  ),
];

/// AUH = Asma Ul-Husna
enum AUH {
  Ar__Rahman,
  Ar__Rahim,
  Al__Malik,
  Al__Quddus,
  As__Salam,
  Al__Mu_a_min,
  Al__Muhaymin,
  Al__Aziz,
  Al__Jabbar,
  Al__Mutakabbir,
  Al__Khaliq,
  Al__Bari_a_,
  Al__Musawwir,
  Al__Ghaffar,
  Al__Qahhar,
  Al__Wahhab,
  Ar__Razzaq,
  Al__Fattah,
  Al___a_Alim,
  Al__Qabid,
  Al__Basit,
  Al__Khafidh,
  Ar__Rafi_a_,
  Al__Mu_a_izz,
  Al__Muzill,
  As__Sami_a_,
  Al__Basir,
  Al__Hakam,
  Al___a_Adl,
  Al__Latif,
  Al__Khabir,
  Al__Halim,
  Al___a_Athim,
  Al__Ghafur,
  Ash__Shakur,
  Al___a_Ali,
  Al__Kabir,
  Al__Hafiz,
  Al__Muqit,
  Al__Hasib,
  Al__Jalil,
  Al__Karim,
  Ar__Raqib,
  Al__Mujib,
  Al__Wasi_a_,
  Al__Hakim,
  Al__Wadud,
  Al__Majid,
  Al__Ba_a_ith,
  Ash__Shahid,
  Al__Haqq,
  Al__Wakil,
  Al__Qawi,
  Al__Matin,
  Al__Wali,
  Al__Hamid,
  Al__Muhsi,
  Al__Mubdi,
  Al__Mu_a_id,
  Al__Muhyi,
  Al__Mumit,
  Al__Hayy,
  Al__Qayyum,
  Al__Wajid,
  Al__Maajid,
  Al__Wahid,
  Al__Ahad,
  As__Samad,
  Al__Qadir,
  Al__Muqtadir,
  Al__Muqaddim,
  Al__Mu_a_akhkhir,
  Al__Awwal,
  Al__Akhir,
  Az__Zahir,
  Al__Batin,
  Al__Waali,
  Al__Muta_a_ali,
  Al__Barr,
  At__Tawwab,
  Al__Muntaqim,
  Al___a_Afu,
  Ar__Ra_a_uf,
  Malik_ul__Mulk,
  Dhul__Jalali_Wal__Ikram,
  Al__Muqsit,
  Al__Jami_a_,
  Al__Ghani,
  Al__Mughni,
  Al__Mani_a_,
  Ad__Dharr,
  An__Nafi_a_,
  An__Nur,
  Al__Hadi,
  Al__Badi_a_,
  Al__Baqi,
  Al__Warith,
  Ar__Rashid,
  As__Sabur,
  ;
}
