import 'package:flutter/src/widgets/framework.dart';
import 'package:hapi/relic/relic.dart';
import 'package:hapi/tarikh/event/event_asset.dart';

class Surah extends Relic {
  Surah({
    required Enum e,
    required this.titleTr,
    required this.titleAr,
    required this.titleEn,
    required this.num,
    required this.numEgypt,
    required this.numNoldeke,
    required this.juzBegin,
    this.juzEnd,
    required this.cntVerses,
    required this.cntRuku,
    required this.revelationPlace,
    this.trMuqattaat,
    this.arMuqattaat,
    required this.titleRefersTo, // TODO translate titleRefersTo and mainThemes
    required this.mainThemes,
  }) : super(
          // Event data:
          tvEra: 'i.Quran Revelation',
          startMs: 0, // TODO put in quran revelation dates!
          endMs: 0,
          // Relic data:
          relicType: RELIC_TYPE.Surah,
          e: e,
        );
  final String titleTr;
  final String titleAr;
  final String titleEn;
  final int num;
  final int numEgypt;
  final int numNoldeke;
  final int juzBegin;
  final int? juzEnd;
  final int cntVerses;
  final double cntRuku;
  final String revelationPlace;
  final String? trMuqattaat;
  final String? arMuqattaat;
  final String titleRefersTo;
  final List<String> mainThemes;

  bool get isSingleJuz => juzEnd == null;
  bool get isMultiJuz => juzEnd != null;

  bool get isMuqattaat => trMuqattaat != null;

  @override
  // TODO: implement widget
  Widget get widget => throw UnimplementedError();

  @override
  RelicAsset getRelicAsset({width = 200.0, height = 200.0, scale = 1.0}) =>
      RelicAsset(
        //'assets/images/surah/${e.name}.png',
        'assets/images/logo/logo.png', // TODO asdf: implement getRelicAsset
        width: width,
        height: height,
        scale: scale,
      );
}

final List<Surah> relicsSurah = [
  Surah(
    e: S.Al_Fatihah,
    titleTr: 'Al-Fatihah',
    titleAr: 'ٱلْفَاتِحَة',
    titleEn: 'The Opening',
    num: 1,
    numEgypt: 5,
    numNoldeke: 48,
    juzBegin: 1,
    juzEnd: null,
    cntVerses: 7,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: [
      'The fundamental principles of the Quran in a condensed form.'
    ],
  ),
  Surah(
    e: S.Al_Baqarah,
    titleTr: 'Al-Baqarah',
    titleAr: 'ٱلْبَقَرَة',
    titleEn: 'The Cow',
    num: 2,
    numEgypt: 87,
    numNoldeke: 91,
    juzBegin: 1,
    juzEnd: 3,
    cntVerses: 286,
    cntRuku: 40,
    revelationPlace: 'Madinah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 67-73',
    mainThemes: [
      'The necessity of God-consciousness.',
      'The error(s) committed by followers of earlier revelations.',
      'Legal ordinances (ethics, social relations, warfare etc.).',
      'Ibrahim',
      'Kaaba',
      'Ayatul Kursi. (v. 255)'
    ],
  ),
  Surah(
    e: S.Aali_Imran,
    titleTr: "Aali 'Imran",
    titleAr: 'آلِ عِمْرَان',
    titleEn: 'The Family Of Imran',
    num: 3,
    numEgypt: 89,
    numNoldeke: 97,
    juzBegin: 3,
    juzEnd: 4,
    cntVerses: 200,
    cntRuku: 20,
    revelationPlace: 'Madinah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 33, 35',
    mainThemes: [
      'The human nature of Isa.',
      'The oneness of Allah.',
      "Man's faith and temptations.",
      'The Battle of Uhud (3 AH).'
    ],
  ),
  Surah(
    e: S.An_Nisa,
    titleTr: 'An-Nisa',
    titleAr: 'ٱلنِّسَاء',
    titleEn: 'The Women',
    num: 4,
    numEgypt: 92,
    numNoldeke: 100,
    juzBegin: 4,
    juzEnd: 6,
    cntVerses: 176,
    cntRuku: 24,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: [
      'Unity of the human race and the mutual obligations of men and women towards one another. (v. 1)',
      'Rights of women.',
      'Questions related to family life (including marriage and inheritance).',
      'Peace and war.',
      'Relations of believers with unbelievers.',
      'Striving in the Cause of Allah (Jihad). (v. 95–97) [10]'
    ],
  ),
  Surah(
    e: S.Al_Maidah,
    titleTr: "Al-Ma'idah",
    titleAr: 'ٱلْمَائِدَة',
    titleEn: 'The Table',
    num: 5,
    numEgypt: 112,
    numNoldeke: 114,
    juzBegin: 6,
    juzEnd: 7,
    cntVerses: 120,
    cntRuku: 16,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 112-114',
    mainThemes: [
      'A series of ordinances (incl. Religious rites and social obligations).',
      'Corruption of the original message of the Injeel by Jews and Christians. (v. 68–77, 116–118)'
    ],
  ),
  Surah(
    e: S.Al_Anam,
    titleTr: "Al-An'am",
    titleAr: 'ٱلْأَنْعَام',
    titleEn: 'The Cattle',
    num: 6,
    numEgypt: 55,
    numNoldeke: 89,
    juzBegin: 7,
    juzEnd: 8,
    cntVerses: 165,
    cntRuku: 20,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 136ff.',
    mainThemes: [
      'Human nature of Muhammad. (v. 50)',
      'Oneness and uniqueness of Allah. (e.g. v. 100, 103)',
      'Pre-Islamic superstitions concerning animals. (v. 136ff)'
    ],
  ),
  Surah(
    e: S.Al_Araf,
    titleTr: "Al-A'raf",
    titleAr: 'ٱلْأَعْرَاف',
    titleEn: 'The Heights',
    num: 7,
    numEgypt: 39,
    numNoldeke: 87,
    juzBegin: 8,
    juzEnd: 9,
    cntVerses: 206,
    cntRuku: 24,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Mim Sad',
    arMuqattaat: 'المص',
    titleRefersTo: 'v. 46, 48',
    mainThemes: [
      'The mission of the prophets.',
      'Adam, Hawwa and Iblis. (v. 16–25)',
      'Stories of Nuh, Hud, Salih, Lut, Shuáyb and Musa. (v. 59–171)',
      "Allah's Covenant with humanity. (v. 172) [11]",
      "What happens to those who discard Allah's message. (v. 175)"
    ],
  ),
  Surah(
    e: S.Al_Anfal,
    titleTr: 'Al-Anfal',
    titleAr: 'ٱلْأَنْفَال',
    titleEn: 'The Spoils Of War',
    num: 8,
    numEgypt: 88,
    numNoldeke: 95,
    juzBegin: 9,
    juzEnd: 10,
    cntVerses: 75,
    cntRuku: 10,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'The Battle of Badr (2 A.H.).',
      'Doctrine of sacrifice through action.'
    ],
  ),
  Surah(
    e: S.At_Tawbah,
    titleTr: 'At-Tawbah',
    titleAr: 'ٱلتَّوْبَة',
    titleEn: 'The Repentance',
    num: 9,
    numEgypt: 113,
    numNoldeke: 113,
    juzBegin: 10,
    juzEnd: 11,
    cntVerses: 129,
    cntRuku: 16,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: '',
    mainThemes: [
      'Problems of war between believers and their enemies.',
      'The expedition to Tabuk (9 A.H.).',
      'Prohibition of intercalation in the Islamic lunar calendar(v. 37) [10]',
      'Those who cannot attain to faith. (v. 124–127)'
    ],
  ),
  Surah(
    e: S.Yunus,
    titleTr: 'Yunus',
    titleAr: 'يُونُس',
    titleEn: 'Yunus',
    num: 10,
    numEgypt: 51,
    numNoldeke: 84,
    juzBegin: 11,
    juzEnd: null,
    cntVerses: 109,
    cntRuku: 11,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'v. 98',
    mainThemes: [
      "The revelation of the Quran to Muhammad (not Muhammad's own work). (v. 15–17, 37–38, 94)",
      'References to earlier prophets.',
      'Fundamental tenets of Islam.'
    ],
  ),
  Surah(
    e: S.Hud,
    titleTr: 'Hud',
    titleAr: 'هُود',
    titleEn: 'Hud',
    num: 11,
    numEgypt: 52,
    numNoldeke: 75,
    juzBegin: 11,
    juzEnd: 12,
    cntVerses: 123,
    cntRuku: 10,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'v. 50-60',
    mainThemes: [
      "The revelation of God's will through his prophets.",
      'More stories of earlier prophets.',
      'Just dealings between men.'
    ],
  ),
  Surah(
    e: S.Yusuf,
    titleTr: 'Yusuf',
    titleAr: 'يُوسُف',
    titleEn: 'Yusuf',
    num: 12,
    numEgypt: 53,
    numNoldeke: 77,
    juzBegin: 12,
    juzEnd: 13,
    cntVerses: 111,
    cntRuku: 12,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'Whole Surah',
    mainThemes: [
      "The story of the prophet Joseph (as an illustration of God's unfathomable direction of men's affairs)."
    ],
  ),
  Surah(
    e: S.Ar_Rad,
    titleTr: "Ar-Ra'd",
    titleAr: 'ٱلرَّعْد',
    titleEn: 'The Thunder',
    num: 13,
    numEgypt: 96,
    numNoldeke: 90,
    juzBegin: 13,
    juzEnd: null,
    cntVerses: 43,
    cntRuku: 6,
    revelationPlace: 'Madinah',
    trMuqattaat: 'Alif Lam Mim Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'v. 13',
    mainThemes: [
      "God's revelation, through his prophets, of certain fundamental moral truths, and the consequences of accepting or rejecting them."
    ],
  ),
  Surah(
    e: S.Ibrahim,
    titleTr: 'Ibrahim',
    titleAr: 'إِبْرَاهِيم',
    titleEn: 'Ibrahim',
    num: 14,
    numEgypt: 72,
    numNoldeke: 76,
    juzBegin: 13,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 7,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'v. 35-41',
    mainThemes: [
      "The revelation of God's word to all mankind, destined to lead man from darkness to light."
    ],
  ),
  Surah(
    e: S.Al_Hijr,
    titleTr: 'Al-Hijr',
    titleAr: 'ٱلْحِجْر',
    titleEn: 'The Rocky Tract',
    num: 15,
    numEgypt: 54,
    numNoldeke: 57,
    juzBegin: 14,
    juzEnd: null,
    cntVerses: 99,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Ra',
    arMuqattaat: 'الر',
    titleRefersTo: 'v. 80',
    mainThemes: [
      "God's guidance to man through revelation of the Quran, which will remain uncorrupted for all times. (v. 9)"
    ],
  ),
  Surah(
    e: S.An_Nahl,
    titleTr: 'An-Nahl',
    titleAr: 'ٱلنَّحْل',
    titleEn: 'The Bee',
    num: 16,
    numEgypt: 70,
    numNoldeke: 73,
    juzBegin: 14,
    juzEnd: null,
    cntVerses: 128,
    cntRuku: 16,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 68-69',
    mainThemes: [
      "God's creativeness:Manifested in the instincts of the bee.",
      'Culmination: Guidance through his revealed word.'
    ],
  ),
  Surah(
    e: S.Al_Isra,
    titleTr: 'Al-Isra',
    titleAr: 'ٱلْإِسْرَاء',
    titleEn: 'The Night Journey',
    num: 17,
    numEgypt: 50,
    numNoldeke: 67,
    juzBegin: 15,
    juzEnd: null,
    cntVerses: 111,
    cntRuku: 12,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      "Muhammad's Night journey from Mecca to Jerusalem.",
      'The children of Israel. (v. 2–8, 101–104)'
    ],
  ),
  Surah(
    e: S.Al_Kahf,
    titleTr: 'Al-Kahf',
    titleAr: 'ٱلْكَهْف',
    titleEn: 'The Cave',
    num: 18,
    numEgypt: 69,
    numNoldeke: 69,
    juzBegin: 15,
    juzEnd: 16,
    cntVerses: 110,
    cntRuku: 12,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 13-20',
    mainThemes: [
      'A series of parables or allegories on the theme of faith in God versus excessive attachment to the life of this world. Including:The men of the cave. (v. 13–20)',
      'The rich man and the poor man. (v. 32–44)',
      'Moses and the unnamed sage. (v. 60–82)',
      'The allegory of ‘Dhu’l-Qarnayn, the Two-Horned One’. (v. 83–98)'
    ],
  ),
  Surah(
    e: S.Maryam,
    titleTr: 'Maryam',
    titleAr: 'مَرْيَم',
    titleEn: 'Maryam',
    num: 19,
    numEgypt: 44,
    numNoldeke: 58,
    juzBegin: 16,
    juzEnd: null,
    cntVerses: 98,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: "Kaf Ha Ya 'Ayn Sad",
    arMuqattaat: 'كهيعص',
    titleRefersTo: 'v. 16-37',
    mainThemes: [
      'The story of Zachariah and his son John, the precursor of Jesus. (v. 2–15)',
      'The story of Mary and Jesus. (v. 16–37)'
    ],
  ),
  Surah(
    e: S.Ta_Ha,
    titleTr: 'Ta-Ha',
    titleAr: 'طه',
    titleEn: 'Ta-Ha',
    num: 20,
    numEgypt: 45,
    numNoldeke: 55,
    juzBegin: 16,
    juzEnd: null,
    cntVerses: 135,
    cntRuku: 8,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ta Ha',
    arMuqattaat: 'طه',
    titleRefersTo: 'v. 1',
    mainThemes: [
      'The guidance offered by God through his prophets.',
      'The fundamental truths inherent in all revealed religions are identical.The story of Moses. (v. 9-98)'
    ],
  ),
  Surah(
    e: S.Al_Anbiya,
    titleTr: 'Al-Anbiya',
    titleAr: 'ٱلْأَنْبِيَاء',
    titleEn: 'The Prophets',
    num: 21,
    numEgypt: 73,
    numNoldeke: 65,
    juzBegin: 17,
    juzEnd: null,
    cntVerses: 112,
    cntRuku: 7,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 48-91',
    mainThemes: [
      'The oneness, uniqueness and transcendence of God.',
      'The continuity and intrinsic unity of all divine revelation.Stories of the prophets of old. (v. 48–91)',
      'The believers of all faiths belong to one single community. (v. 92)'
    ],
  ),
  Surah(
    e: S.Al_Hajj,
    titleTr: 'Al-Hajj',
    titleAr: 'ٱلْحَجّ',
    titleEn: 'The Pilgrimage',
    num: 22,
    numEgypt: 103,
    numNoldeke: 107,
    juzBegin: 17,
    juzEnd: null,
    cntVerses: 78,
    cntRuku: 10,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 25-38',
    mainThemes: [
      'The Mecca pilgrimage and some of the rituals connected with it. (v. 25–38)'
    ],
  ),
  Surah(
    e: S.Al_Muminun,
    titleTr: "Al-Mu'minun",
    titleAr: 'ٱلْمُؤْمِنُون',
    titleEn: 'The Believers',
    num: 23,
    numEgypt: 74,
    numNoldeke: 64,
    juzBegin: 18,
    juzEnd: null,
    cntVerses: 118,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'True faith.',
      "The evidence of the existence of an almighty Creator, and man's ultimate responsibility before Him.",
      "The unity of all religious communities, broken by man's egotism, greed and striving after power. (v. 52–53)",
      'The impossibility to believe in God, without believing in life after death.'
    ],
  ),
  Surah(
    e: S.An_Nur,
    titleTr: 'An-Nur',
    titleAr: 'ٱلنُّور',
    titleEn: 'The Light',
    num: 24,
    numEgypt: 102,
    numNoldeke: 105,
    juzBegin: 18,
    juzEnd: null,
    cntVerses: 64,
    cntRuku: 9,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 35',
    mainThemes: [
      'Mutual relations and ethical rules between men and women.',
      'The mystic parable of the ‘light of God’ (\"Verse of Light\"). (v. 35)'
    ],
  ),
  Surah(
    e: S.Al_Furqan,
    titleTr: 'Al-Furqan',
    titleAr: 'ٱلْفُرْقَان',
    titleEn: 'The Criterion',
    num: 25,
    numEgypt: 42,
    numNoldeke: 66,
    juzBegin: 18,
    juzEnd: 19,
    cntVerses: 77,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'The purpose of every divine revelation is to provide a stable criterion of true and false.',
      'The humanness of every apostle sent by God to man. (v. 20)',
      "Divine revelation belongs to God's creative activity."
    ],
  ),
  Surah(
    e: S.Ash_Shuara,
    titleTr: "Ash-Shu'ara",
    titleAr: 'ٱلشُّعَرَاء',
    titleEn: 'The Poets',
    num: 26,
    numEgypt: 47,
    numNoldeke: 56,
    juzBegin: 19,
    juzEnd: null,
    cntVerses: 227,
    cntRuku: 11,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ta Sin Mim',
    arMuqattaat: 'طسم',
    titleRefersTo: 'v. 224',
    mainThemes: [
      "Man's weakness, which causes him to reject God's message and worship power and wealth etc."
    ],
  ),
  Surah(
    e: S.An_Naml,
    titleTr: 'An-Naml',
    titleAr: 'ٱلنَّمْل',
    titleEn: 'The Ant',
    num: 27,
    numEgypt: 48,
    numNoldeke: 68,
    juzBegin: 19,
    juzEnd: 20,
    cntVerses: 93,
    cntRuku: 7,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ta Sin',
    arMuqattaat: 'طس',
    titleRefersTo: 'v. 18',
    mainThemes: ['The legend of king Solomon and queen of Sheba.'],
  ),
  Surah(
    e: S.Al_Qasas,
    titleTr: 'Al-Qasas',
    titleAr: 'ٱلْقَصَص',
    titleEn: 'The Stories',
    num: 28,
    numEgypt: 49,
    numNoldeke: 79,
    juzBegin: 20,
    juzEnd: null,
    cntVerses: 88,
    cntRuku: 9,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ta Sin Mim',
    arMuqattaat: 'طسم',
    titleRefersTo: 'v. 25',
    mainThemes: ['Human aspects of the life of Moses.'],
  ),
  Surah(
    e: S.Al_Ankabut,
    titleTr: 'Al-Ankabut',
    titleAr: 'ٱلْعَنْكَبُوت',
    titleEn: 'The Spider',
    num: 29,
    numEgypt: 85,
    numNoldeke: 81,
    juzBegin: 20,
    juzEnd: 21,
    cntVerses: 69,
    cntRuku: 7,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 41',
    mainThemes: [
      'The parable of ‘the spider house’, a symbol of false beliefs that are destined to be blown away by the winds of truth. (v. 41)'
    ],
  ),
  Surah(
    e: S.Ar_Rum,
    titleTr: 'Ar-Rum',
    titleAr: 'ٱلرُّوم',
    titleEn: 'The Romans',
    num: 30,
    numEgypt: 84,
    numNoldeke: 74,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 60,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Predictions of the near victory of the Byzantines [over the Persians] and the Battle of Badr (2 A.H.). (v. 1–7)',
      "God's ability to resurrect the dead at the end of time, and the people's ignorance of this."
    ],
  ),
  Surah(
    e: S.Luqmaan,
    titleTr: 'Luqmaan',
    titleAr: 'لُقْمَان',
    titleEn: 'Luqman',
    num: 31,
    numEgypt: 57,
    numNoldeke: 82,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 34,
    cntRuku: 4,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 12-19',
    mainThemes: [
      'The story of Luqman, a legendary sage, counselling his son. (v. 12–19)'
    ],
  ),
  Surah(
    e: S.As_Sajdah,
    titleTr: 'As-Sajdah',
    titleAr: 'ٱلسَّجْدَة',
    titleEn: 'The Prostration',
    num: 32,
    numEgypt: 75,
    numNoldeke: 70,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 3,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Alif Lam Mim',
    arMuqattaat: 'الم',
    titleRefersTo: 'v. 15',
    mainThemes: [
      "God's creation.[12]",
      "God's revelation and man's acceptance or denial.[12]",
      'The Day of Judgement.[12]'
    ],
  ),
  Surah(
    e: S.Al_Ahzaab,
    titleTr: 'Al-Ahzaab',
    titleAr: 'ٱلْأَحْزَاب',
    titleEn: 'The Clans',
    num: 33,
    numEgypt: 90,
    numNoldeke: 103,
    juzBegin: 21,
    juzEnd: 22,
    cntVerses: 73,
    cntRuku: 9,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 9-27',
    mainThemes: [
      'The War of the Confederates (5 A.H.). (v. 9-27)',
      'The relationship between Muhammad and his family.'
    ],
  ),
  Surah(
    e: S.Saba,
    titleTr: 'Saba',
    titleAr: 'سَبَأ',
    titleEn: 'Sheba',
    num: 34,
    numEgypt: 58,
    numNoldeke: 85,
    juzBegin: 22,
    juzEnd: null,
    cntVerses: 54,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 15-20',
    mainThemes: [
      'The insignificance of the knowledge accessible to man. (v. 9)',
      'The story of the people of Sheba, as an example of the impermanence of human power, wealth and glory. (v. 15–20)',
      'Always be conscious of God. (v. 46)'
    ],
  ),
  Surah(
    e: S.Faatir,
    titleTr: 'Faatir',
    titleAr: 'فَاطِر',
    titleEn: 'The Originator',
    num: 35,
    numEgypt: 43,
    numNoldeke: 86,
    juzBegin: 22,
    juzEnd: null,
    cntVerses: 45,
    cntRuku: 5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      "God's power to create and resurrect.",
      "God's revelation of his will through his prophets."
    ],
  ),
  Surah(
    e: S.Ya_Sin,
    titleTr: 'Ya-Sin',
    titleAr: 'يس',
    titleEn: 'Ya-Sin',
    num: 36,
    numEgypt: 41,
    numNoldeke: 60,
    juzBegin: 22,
    juzEnd: 23,
    cntVerses: 83,
    cntRuku: 5,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Yaseen',
    arMuqattaat: 'يس',
    titleRefersTo: 'v. 1',
    mainThemes: [
      "Man's moral responsibility, resurrection and God's judgment.",
      'To be recited over the dying and in the prayers of the dead.'
    ],
  ),
  Surah(
    e: S.As_Saaffaat,
    titleTr: 'As-Saaffaat',
    titleAr: 'ٱلصَّافَّات',
    titleEn: 'Those Drawn up In Ranks',
    num: 37,
    numEgypt: 56,
    numNoldeke: 50,
    juzBegin: 23,
    juzEnd: null,
    cntVerses: 182,
    cntRuku: 5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Resurrection and the certainty that all human beings will have to answer before God.',
      "Man's constant need of prophetic guidance.Stories of earlier prophets. (v. 75–148)"
    ],
  ),
  Surah(
    e: S.Saad,
    titleTr: 'Saad',
    titleAr: 'ص',
    titleEn: 'Saad',
    num: 38,
    numEgypt: 38,
    numNoldeke: 59,
    juzBegin: 23,
    juzEnd: null,
    cntVerses: 88,
    cntRuku: 5,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Sad',
    arMuqattaat: 'ص',
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Divine guidance and its rejection by those who are lost in fast pride.'
    ],
  ),
  Surah(
    e: S.Az_Zumar,
    titleTr: 'Az-Zumar',
    titleAr: 'ٱلزُّمَر',
    titleEn: 'The Groups',
    num: 39,
    numEgypt: 59,
    numNoldeke: 80,
    juzBegin: 23,
    juzEnd: 24,
    cntVerses: 75,
    cntRuku: 8,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 71, 73',
    mainThemes: [
      'The evidence of the existence and oneness of God in all manifestations of nature.',
      'God forgives all sins to him who repents before his death.',
      'Allegories of the Last Hour and the Day of Judgment.'
    ],
  ),
  Surah(
    e: S.Ghafir,
    titleTr: 'Ghafir',
    titleAr: 'غَافِر',
    titleEn: 'The Forgiver',
    num: 40,
    numEgypt: 60,
    numNoldeke: 78,
    juzBegin: 24,
    juzEnd: null,
    cntVerses: 85,
    cntRuku: 9,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 3',
    mainThemes: [
      "Man's false pride, worship of false values (wealth, power etc.) and his denial of divine guidance.Stories of earlier prophets."
    ],
  ),
  Surah(
    e: S.Fussilat,
    titleTr: 'Fussilat',
    titleAr: 'فُصِّلَت',
    titleEn: 'Explained in Detail',
    num: 41,
    numEgypt: 61,
    numNoldeke: 71,
    juzBegin: 24,
    juzEnd: 25,
    cntVerses: 54,
    cntRuku: 6,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 3',
    mainThemes: ["Man's acceptance or rejection of divine revelation."],
  ),
  Surah(
    e: S.Ash_Shura,
    titleTr: 'Ash-Shura',
    titleAr: 'ٱلشُّورىٰ',
    titleEn: 'The Consultation',
    num: 42,
    numEgypt: 62,
    numNoldeke: 83,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 53,
    cntRuku: 5,
    revelationPlace: 'Makkah',
    trMuqattaat: "Ha Mim 'Ayn Sin Qaf",
    arMuqattaat: 'حم عسق',
    titleRefersTo: 'v. 36',
    mainThemes: [
      'God is undefinable and unfathomable. (v. 11, 16)',
      'All prophets taught the oneness of God, so all believers of all ‘denominations’ should see themselves as ‘one single community’. (v. 13, 15)',
      'The law of cause and effect: In the life to come man will only harvest ‘what his own hands have wrought’ in this world.'
    ],
  ),
  Surah(
    e: S.Az_Zukhruf,
    titleTr: 'Az-Zukhruf',
    titleAr: 'ٱلْزُّخْرُف',
    titleEn: 'Ornaments of Gold',
    num: 43,
    numEgypt: 63,
    numNoldeke: 61,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 89,
    cntRuku: 7,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 35',
    mainThemes: [
      'To equal anyone or anything with God is sprititually destructive and logically unacceptable.',
      "People's blind adherence to the faith of their forefathers. (v. 22–23)"
    ],
  ),
  Surah(
    e: S.Ad_Dukhaan,
    titleTr: 'Ad-Dukhaan',
    titleAr: 'ٱلدُّخَان',
    titleEn: 'The Smoke',
    num: 44,
    numEgypt: 64,
    numNoldeke: 53,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 59,
    cntRuku: 3,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 10',
    mainThemes: [
      'Through revelation worldly pride is eventually brought to naught.[12]'
    ],
  ),
  Surah(
    e: S.Al_Jaathiyah,
    titleTr: 'Al-Jaathiyah',
    titleAr: 'ٱلْجَاثِيَة',
    titleEn: 'The Crouching',
    num: 45,
    numEgypt: 65,
    numNoldeke: 72,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 37,
    cntRuku: 4,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 28',
    mainThemes: [
      'The humility with which all human beings will face their final judgment on resurrection. (v. 28)'
    ],
  ),
  Surah(
    e: S.Al_Ahqaaf,
    titleTr: 'Al-Ahqaaf',
    titleAr: 'ٱلْأَحْقَاف',
    titleEn: 'The Dunes',
    num: 46,
    numEgypt: 66,
    numNoldeke: 88,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 35,
    cntRuku: 4.5,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Ha Mim',
    arMuqattaat: 'حم',
    titleRefersTo: 'v. 21',
    mainThemes: [
      'Warning the disbelievers of their miserable fate, and reassuring the believers of their salvation.'
    ],
  ),
  Surah(
    e: S.Muhammad,
    titleTr: 'Muhammad',
    titleAr: 'مُحَمَّد',
    titleEn: 'Muhammad',
    num: 47,
    numEgypt: 95,
    numNoldeke: 96,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 38,
    cntRuku: 4,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 2',
    mainThemes: [
      "Fighting (qital) in God's cause.",
      'Instructions for Muslims to be virtuous to their parents.',
      'The Story of Hud and the punishment of that befell his people.',
      'Advising Muhammad to be more patient in delivering Islam'
    ],
  ),
  Surah(
    e: S.Al_Fath,
    titleTr: 'Al-Fath',
    titleAr: 'ٱلْفَتْح',
    titleEn: 'The Victory',
    num: 48,
    numEgypt: 111,
    numNoldeke: 108,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 4.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The Truce of Hudaybiyyah (6 A.H.).'],
  ),
  Surah(
    e: S.Al_Hujuraat,
    titleTr: 'Al-Hujuraat',
    titleAr: 'ٱلْحُجُرَات',
    titleEn: 'The Inner Apartments',
    num: 49,
    numEgypt: 106,
    numNoldeke: 112,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 18,
    cntRuku: 2.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 4',
    mainThemes: [
      'Social ethics.Reverence to Muhammad and the righteous leaders after him.',
      'The brotherhood of all believers and all mankind. (v. 10, 13)',
      'The difference between true faith and outward observance of religious formalities. (v. 14 ff.)'
    ],
  ),
  Surah(
    e: S.Qaaf,
    titleTr: 'Qaaf',
    titleAr: 'ق',
    titleEn: 'Qaf',
    num: 50,
    numEgypt: 34,
    numNoldeke: 54,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 45,
    cntRuku: 3,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Qaf',
    arMuqattaat: 'ق',
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Death and resurrection.',
      'God is closer to man than his neck-vein. (v. 16)[12]'
    ],
  ),
  Surah(
    e: S.Adh_Dhaariyaat,
    titleTr: 'Adh-Dhaariyaat',
    titleAr: 'ٱلذَّارِيَات',
    titleEn: 'The Winnowing Winds',
    num: 51,
    numEgypt: 67,
    numNoldeke: 39,
    juzBegin: 26,
    juzEnd: 27,
    cntVerses: 60,
    cntRuku: 2.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Destruction of those who denied the messengers, and a warning for those who deny the truth.'
    ],
  ),
  Surah(
    e: S.At_Tur,
    titleTr: 'At-Tur',
    titleAr: 'ٱلطُّور',
    titleEn: 'The Mount',
    num: 52,
    numEgypt: 76,
    numNoldeke: 40,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 49,
    cntRuku: 2.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.An_Najm,
    titleTr: 'An-Najm',
    titleAr: 'ٱلنَّجْم',
    titleEn: 'The Star',
    num: 53,
    numEgypt: 23,
    numNoldeke: 28,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 62,
    cntRuku: 2.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      "Muhammad's experience of an ascension to heaven (Mi’raj, including his vision of the Sidrat al-Muntaha, the Lote-Tree of the Extremity). (v. 13–18)"
    ],
  ),
  Surah(
    e: S.Al_Qamar,
    titleTr: 'Al-Qamar',
    titleAr: 'ٱلْقَمَر',
    titleEn: 'The Moon',
    num: 54,
    numEgypt: 37,
    numNoldeke: 49,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 55,
    cntRuku: 2.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Ar_Rahman,
    titleTr: 'Ar-Rahman',
    titleAr: 'ٱلرَّحْمَٰن',
    titleEn: 'The Most Merciful',
    num: 55,
    numEgypt: 97,
    numNoldeke: 43,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 78,
    cntRuku: 3,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Everything will pass away, except the face of God. (v. 26–27)[12]',
      'Description of paradise. (v. 46–78)[10]'
    ],
  ),
  Surah(
    e: S.Al_Waqiah,
    titleTr: "Al-Waqi'ah",
    titleAr: 'ٱلْوَاقِعَة',
    titleEn: 'The Event',
    num: 56,
    numEgypt: 46,
    numNoldeke: 41,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 96,
    cntRuku: 3.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Description of life in the Hereafter for the believers and the disblievers.[13]'
    ],
  ),
  Surah(
    e: S.Al_Hadid,
    titleTr: 'Al-Hadid',
    titleAr: 'ٱلْحَدِيد',
    titleEn: 'The Iron',
    num: 57,
    numEgypt: 94,
    numNoldeke: 99,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 4,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 25',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Mujadilah,
    titleTr: 'Al-Mujadilah',
    titleAr: 'ٱلْمُجَادِلَة',
    titleEn: 'The Pleading Woman',
    num: 58,
    numEgypt: 105,
    numNoldeke: 106,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 22,
    cntRuku: 3.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Divorce.',
      'Faith and denial.',
      'Hypocrisy.',
      'The attitude believers should have toward non-believers.'
    ],
  ),
  Surah(
    e: S.Al_Hashr,
    titleTr: 'Al-Hashr',
    titleAr: 'ٱلْحَشْر',
    titleEn: 'The Gathering',
    num: 59,
    numEgypt: 101,
    numNoldeke: 102,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 24,
    cntRuku: 3.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 2',
    mainThemes: [
      'The conflict between the Muslim coummunity and the Jewish tribe of Banu’n-Nadir of Medina.'
    ],
  ),
  Surah(
    e: S.Al_Mumtahanah,
    titleTr: 'Al-Mumtahanah',
    titleAr: 'ٱلْمُمْتَحَنَة',
    titleEn: 'The Examined One',
    num: 60,
    numEgypt: 91,
    numNoldeke: 110,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 13,
    cntRuku: 2.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 10',
    mainThemes: ['The believers’ relations with unbelievers.'],
  ),
  Surah(
    e: S.As_Saff,
    titleTr: 'As-Saff',
    titleAr: 'ٱلصَّفّ',
    titleEn: 'The Ranks',
    num: 61,
    numEgypt: 109,
    numNoldeke: 98,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 14,
    cntRuku: 1.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 4',
    mainThemes: [
      'A call to unity between professed belief and actual behaviour.'
    ],
  ),
  Surah(
    e: S.Al_Jumuah,
    titleTr: "Al-Jumu'ah",
    titleAr: 'ٱلْجُمُعَة',
    titleEn: 'Friday',
    num: 62,
    numEgypt: 110,
    numNoldeke: 94,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 1.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 9-10',
    mainThemes: ['Obligatory congregational prayer on Friday.'],
  ),
  Surah(
    e: S.Al_Munafiqun,
    titleTr: 'Al-Munafiqun',
    titleAr: 'ٱلْمُنَافِقُون',
    titleEn: 'The Hypocrites',
    num: 63,
    numEgypt: 104,
    numNoldeke: 104,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 1.5,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: ['Hypocrisy.'],
  ),
  Surah(
    e: S.At_Taghabun,
    titleTr: 'At-Taghabun',
    titleAr: 'ٱلتَّغَابُن',
    titleEn: 'Mutual Disillusion',
    num: 64,
    numEgypt: 108,
    numNoldeke: 93,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 18,
    cntRuku: 2,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 9',
    mainThemes: [''],
  ),
  Surah(
    e: S.At_Talaq,
    titleTr: 'At-Talaq',
    titleAr: 'ٱلطَّلَاق',
    titleEn: 'The Divorce',
    num: 65,
    numEgypt: 99,
    numNoldeke: 101,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 12,
    cntRuku: 2,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: ['Divorce (waiting period, remarriage).'],
  ),
  Surah(
    e: S.At_Tahrim,
    titleTr: 'At-Tahrim',
    titleAr: 'ٱلتَّحْرِيم',
    titleEn: 'The Prohibition',
    num: 66,
    numEgypt: 107,
    numNoldeke: 109,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 12,
    cntRuku: 2,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ["Certain aspects of Muhammad's personal and family life."],
  ),
  Surah(
    e: S.Al_Mulk,
    titleTr: 'Al-Mulk',
    titleAr: 'ٱلْمُلْك',
    titleEn: 'The Sovereignty',
    num: 67,
    numEgypt: 77,
    numNoldeke: 63,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      "Man's inability to understand the mysteries of the universe, and his dependence on guidance through divine revelation.",
      "The manifestation of God's absolute perfection in creation through the fine tuning of the universe."
    ],
  ),
  Surah(
    e: S.Al_Qalam,
    titleTr: 'Al-Qalam',
    titleAr: 'ٱلْقَلَم',
    titleEn: 'The Pen',
    num: 68,
    numEgypt: 2,
    numNoldeke: 18,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 2,
    revelationPlace: 'Makkah',
    trMuqattaat: 'Nun',
    arMuqattaat: 'ن',
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Haaqqa,
    titleTr: 'Al-Haaqqa',
    titleAr: 'ٱلْحَاقَّة',
    titleEn: 'The Reality',
    num: 69,
    numEgypt: 78,
    numNoldeke: 38,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 2,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Maaarij,
    titleTr: "Al-Ma'aarij",
    titleAr: 'ٱلْمَعَارِج',
    titleEn: 'The Ascending Stairways',
    num: 70,
    numEgypt: 79,
    numNoldeke: 42,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 44,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 3',
    mainThemes: [
      'The unwillingness to believe, caused by the restlessness inherent in human nature.'
    ],
  ),
  Surah(
    e: S.Nuh,
    titleTr: 'Nuh',
    titleAr: 'نُوح',
    titleEn: 'Nuh',
    num: 71,
    numEgypt: 71,
    numNoldeke: 51,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 28,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: [
      'The story of Noah.The struggle against blind materialism and the lack of spiritual values.'
    ],
  ),
  Surah(
    e: S.Al_Jinn,
    titleTr: 'Al-Jinn',
    titleAr: 'ٱلْجِنّ',
    titleEn: 'The Jinn',
    num: 72,
    numEgypt: 40,
    numNoldeke: 62,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 28,
    cntRuku: 2,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Muzzammil,
    titleTr: 'Al-Muzzammil',
    titleAr: 'ٱلْمُزَّمِّل',
    titleEn: 'The Enshrouded One',
    num: 73,
    numEgypt: 3,
    numNoldeke: 23,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 20,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['Loosening the strict regulation on night prayer.'],
  ),
  Surah(
    e: S.Al_Muddaththir,
    titleTr: 'Al-Muddaththir',
    titleAr: 'ٱلْمُدَّثِّر',
    titleEn: 'The Cloaked One',
    num: 74,
    numEgypt: 4,
    numNoldeke: 2,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 56,
    cntRuku: 2,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'This short early surah outlines almost all fundamental Quranic concepts.',
      "God's promise of eternal damnation for the disbelievers."
    ],
  ),
  Surah(
    e: S.Al_Qiyamah,
    titleTr: 'Al-Qiyamah',
    titleAr: 'ٱلْقِيَامَة',
    titleEn: 'The Resurrection',
    num: 75,
    numEgypt: 31,
    numNoldeke: 36,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 40,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The concept of resurrection.'],
  ),
  Surah(
    e: S.Ad_Dahr,
    titleTr: 'Ad-Dahr',
    titleAr: 'ٱلْإِنْسَان',
    titleEn: 'Man',
    num: 76,
    numEgypt: 98,
    numNoldeke: 52,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 31,
    cntRuku: 2,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Mursalaat,
    titleTr: 'Al-Mursalaat',
    titleAr: 'ٱلْمُرْسَلَات',
    titleEn: 'The Emissaries',
    num: 77,
    numEgypt: 33,
    numNoldeke: 32,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 50,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The gradual revelation of the Quran.'],
  ),
  Surah(
    e: S.An_Naba,
    titleTr: "An-Naba'",
    titleAr: 'ٱلنَّبَأ',
    titleEn: 'The Great News',
    num: 78,
    numEgypt: 80,
    numNoldeke: 33,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 40,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 2',
    mainThemes: [
      'Life after death.',
      "Resurrection and God's ultimate judgment."
    ],
  ),
  Surah(
    e: S.An_Naaziaat,
    titleTr: "An-Naazi'aat",
    titleAr: 'ٱلنَّازِعَات',
    titleEn: 'Those Who Drag Forth',
    num: 79,
    numEgypt: 81,
    numNoldeke: 31,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 46,
    cntRuku: 1.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Abasa,
    titleTr: 'Abasa',
    titleAr: 'عَبَسَ',
    titleEn: 'He Frowned',
    num: 80,
    numEgypt: 24,
    numNoldeke: 17,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 42,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.At_Takwir,
    titleTr: 'At-Takwir',
    titleAr: 'ٱلتَّكْوِير',
    titleEn: 'The Overthrowing',
    num: 81,
    numEgypt: 7,
    numNoldeke: 27,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ["The Last Hour and man's resurrection."],
  ),
  Surah(
    e: S.Al_Infitar,
    titleTr: 'Al-Infitar',
    titleAr: 'ٱلْإِنْفِطَار',
    titleEn: 'The Cleaving Asunder',
    num: 82,
    numEgypt: 82,
    numNoldeke: 26,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Mutaffifin,
    titleTr: 'Al-Mutaffifin',
    titleAr: 'ٱلْمُطَفِّفِين',
    titleEn: 'The Dealers in Fraud',
    num: 83,
    numEgypt: 86,
    numNoldeke: 37,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 36,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Inshiqaaq,
    titleTr: 'Al-Inshiqaaq',
    titleAr: 'ٱلْإِنْشِقَاق',
    titleEn: 'The Splitting Asunder',
    num: 84,
    numEgypt: 83,
    numNoldeke: 29,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 25,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Buruj,
    titleTr: 'Al-Buruj',
    titleAr: 'ٱلْبُرُوج',
    titleEn: 'The Constellations',
    num: 85,
    numEgypt: 27,
    numNoldeke: 22,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 22,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.At_Taariq,
    titleTr: 'At-Taariq',
    titleAr: 'ٱلطَّارِق',
    titleEn: 'The Morning Star',
    num: 86,
    numEgypt: 36,
    numNoldeke: 15,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 17,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Ala,
    titleTr: "Al-A'la",
    titleAr: 'ٱلْأَعْلَىٰ',
    titleEn: 'The Most High',
    num: 87,
    numEgypt: 8,
    numNoldeke: 19,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Ghaashiyah,
    titleTr: 'Al-Ghaashiyah',
    titleAr: 'ٱلْغَاشِيَة',
    titleEn: 'The Overwhelming Event',
    num: 88,
    numEgypt: 68,
    numNoldeke: 34,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 26,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Fajr,
    titleTr: 'Al-Fajr',
    titleAr: 'ٱلْفَجْر',
    titleEn: 'The Dawn',
    num: 89,
    numEgypt: 10,
    numNoldeke: 35,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 1,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Balad,
    titleTr: 'Al-Balad',
    titleAr: 'ٱلْبَلَد',
    titleEn: 'The City',
    num: 90,
    numEgypt: 35,
    numNoldeke: 11,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 20,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Ash_Shams,
    titleTr: 'Ash-Shams',
    titleAr: 'ٱلشَّمْس',
    titleEn: 'The Sun',
    num: 91,
    numEgypt: 26,
    numNoldeke: 16,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 15,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Layl,
    titleTr: 'Al-Layl',
    titleAr: 'ٱللَّيْل',
    titleEn: 'The Night',
    num: 92,
    numEgypt: 9,
    numNoldeke: 10,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 21,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Ad_Dhuha,
    titleTr: 'Ad-Dhuha',
    titleAr: 'ٱلضُّحَىٰ',
    titleEn: 'The Forenoon',
    num: 93,
    numEgypt: 11,
    numNoldeke: 13,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      "Man's suffering and God's justice.",
      "A message of hope and consolation is given to man from Allah's past mercies.",
      'Man is bidden to pursue the path of goodness and proclaim the bounties of Allah.',
      'Prophecy regarding the good future for Muhammad.'
    ],
  ),
  Surah(
    e: S.Ash_Sharh,
    titleTr: 'Ash-Sharh',
    titleAr: 'ٱلشَّرْح',
    titleEn: 'The Consolation',
    num: 94,
    numEgypt: 12,
    numNoldeke: 12,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.At_Tin,
    titleTr: 'At-Tin',
    titleAr: 'ٱلتِّين',
    titleEn: 'The Fig',
    num: 95,
    numEgypt: 28,
    numNoldeke: 20,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'A fundamental moral verity, common to all true religious teachings.'
    ],
  ),
  Surah(
    e: S.Al_Alaq,
    titleTr: 'Al-Alaq',
    titleAr: 'ٱلْعَلَق',
    titleEn: 'The Clinging Clot',
    num: 96,
    numEgypt: 1,
    numNoldeke: 1,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 2',
    mainThemes: ['The first five verses revealed to Muhammad. (v. 1–5)'],
  ),
  Surah(
    e: S.Al_Qadr,
    titleTr: 'Al-Qadr',
    titleAr: 'ٱلْقَدْر',
    titleEn: 'The Night of Decree',
    num: 97,
    numEgypt: 25,
    numNoldeke: 14,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The Night of Laylat-ul-Qadr'],
  ),
  Surah(
    e: S.Al_Bayyinah,
    titleTr: 'Al-Bayyinah',
    titleAr: 'ٱلْبَيِّنَة',
    titleEn: 'The Clear Evidence',
    num: 98,
    numEgypt: 100,
    numNoldeke: 92,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 1,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The Evidence, and the clear truth[14]'],
  ),
  Surah(
    e: S.Az_Zalzalah,
    titleTr: 'Az-Zalzalah',
    titleAr: 'ٱلزَّلْزَلَة',
    titleEn: 'The Earthquake',
    num: 99,
    numEgypt: 93,
    numNoldeke: 25,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Aadiyat,
    titleTr: "Al-'Aadiyat",
    titleAr: 'ٱلْعَادِيَات',
    titleEn: 'The Chargers',
    num: 100,
    numEgypt: 14,
    numNoldeke: 30,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Qaariah,
    titleTr: "Al-Qaari'ah",
    titleAr: 'ٱلْقَارِعَة',
    titleEn: 'The Calamity',
    num: 101,
    numEgypt: 30,
    numNoldeke: 24,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.At_Takaathur,
    titleTr: 'At-Takaathur',
    titleAr: 'ٱلتَّكَاثُر',
    titleEn: 'Competition',
    num: 102,
    numEgypt: 16,
    numNoldeke: 8,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ["Man's greed and tendencies."],
  ),
  Surah(
    e: S.Al_Asr,
    titleTr: "Al-'Asr",
    titleAr: 'ٱلْعَصْر',
    titleEn: 'The Declining Day',
    num: 103,
    numEgypt: 13,
    numNoldeke: 21,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Humazah,
    titleTr: 'Al-Humazah',
    titleAr: 'ٱلْهُمَزَة',
    titleEn: 'The Slanderer',
    num: 104,
    numEgypt: 32,
    numNoldeke: 6,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 9,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [''],
  ),
  Surah(
    e: S.Al_Fil,
    titleTr: 'Al-Fil',
    titleAr: 'ٱلْفِيل',
    titleEn: 'The Elephant',
    num: 105,
    numEgypt: 19,
    numNoldeke: 9,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'The Abyssinian attack against Mecca in the year 570 CE, the Year of the Elephant.'
    ],
  ),
  Surah(
    e: S.Quraish,
    titleTr: 'Quraish',
    titleAr: 'قُرَيْش',
    titleEn: 'Quraish',
    num: 106,
    numEgypt: 29,
    numNoldeke: 4,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 4,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'The Quraysh, custodians of the Kaaba, should be thankful to God for protecting them from hunger and danger.[12]'
    ],
  ),
  Surah(
    e: S.Al_Maaun,
    titleTr: "Al-Maa'un",
    titleAr: 'ٱلْمَاعُون',
    titleEn: 'Almsgiving',
    num: 107,
    numEgypt: 17,
    numNoldeke: 7,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 7,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 7',
    mainThemes: [
      'The meaning of true worship through sincere devotion and helping those in need.[12]'
    ],
  ),
  Surah(
    e: S.Al_Kawthar,
    titleTr: 'Al-Kawthar',
    titleAr: 'ٱلْكَوْثَر',
    titleEn: 'Abundance',
    num: 108,
    numEgypt: 15,
    numNoldeke: 5,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: [
      'Spiritual riches through devotion and sacrifice.',
      'Hatred results in the cutting off of all hope.[12]'
    ],
  ),
  Surah(
    e: S.Al_Kaafirun,
    titleTr: 'Al-Kaafirun',
    titleAr: 'ٱلْكَافِرُون',
    titleEn: 'The Disbelievers',
    num: 109,
    numEgypt: 18,
    numNoldeke: 45,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 6,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['The correct attitude towards those who reject faith.[12]'],
  ),
  Surah(
    e: S.An_Nasr,
    titleTr: 'An-Nasr',
    titleAr: 'ٱلنَّصْر',
    titleEn: 'The Help',
    num: 110,
    numEgypt: 114,
    numNoldeke: 111,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: 'Madinah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ["The last complete surah revealed before Muhammad's death."],
  ),
  Surah(
    e: S.Al_Masad,
    titleTr: 'Al-Masad',
    titleAr: 'ٱلْمَسَد',
    titleEn: 'The Palm Fiber',
    num: 111,
    numEgypt: 6,
    numNoldeke: 3,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 5',
    mainThemes: [
      "Allah cursing Abu Lahab and his wife, who was Muhammad's uncle and at the time of the revelation of this verse, Muhammad's brother in law, due to his hostility towards Islam and Prophet Muhammad."
    ],
  ),
  Surah(
    e: S.Al_Ikhlas,
    titleTr: 'Al-Ikhlas',
    titleAr: 'ٱلْإِخْلَاص',
    titleEn: 'The Sincerity',
    num: 112,
    numEgypt: 22,
    numNoldeke: 44,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 4,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: ['The oneness of God.'],
  ),
  Surah(
    e: S.Al_Falaq,
    titleTr: 'Al-Falaq',
    titleAr: 'ٱلْفَلَق',
    titleEn: 'The Daybreak',
    num: 113,
    numEgypt: 20,
    numNoldeke: 46,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'v. 1',
    mainThemes: ['Seek refuge in God from evil of others.[12]'],
  ),
  Surah(
    e: S.An_Naas,
    titleTr: 'An-Naas',
    titleAr: 'ٱلنَّاس',
    titleEn: 'Mankind',
    num: 114,
    numEgypt: 21,
    numNoldeke: 47,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 6,
    cntRuku: 0.333,
    revelationPlace: 'Makkah',
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersTo: 'Whole Surah',
    mainThemes: ["Trust in God's protection from temptations.["],
  ),
];

final List<RelicSetFilter> relicSetFiltersSurah = [
  RelicSetFilter(
    type: FILTER_TYPE.Default,
    tvLabel: 'a.Surah', // TODO asdf
  ),
];

/// S = Surah
enum S {
  Al_Fatihah,
  Al_Baqarah,
  Aali_Imran,
  An_Nisa,
  Al_Maidah,
  Al_Anam,
  Al_Araf,
  Al_Anfal,
  At_Tawbah,
  Yunus,
  Hud,
  Yusuf,
  Ar_Rad,
  Ibrahim,
  Al_Hijr,
  An_Nahl,
  Al_Isra,
  Al_Kahf,
  Maryam,
  Ta_Ha,
  Al_Anbiya,
  Al_Hajj,
  Al_Muminun,
  An_Nur,
  Al_Furqan,
  Ash_Shuara,
  An_Naml,
  Al_Qasas,
  Al_Ankabut,
  Ar_Rum,
  Luqmaan,
  As_Sajdah,
  Al_Ahzaab,
  Saba,
  Faatir,
  Ya_Sin,
  As_Saaffaat,
  Saad,
  Az_Zumar,
  Ghafir,
  Fussilat,
  Ash_Shura,
  Az_Zukhruf,
  Ad_Dukhaan,
  Al_Jaathiyah,
  Al_Ahqaaf,
  Muhammad,
  Al_Fath,
  Al_Hujuraat,
  Qaaf,
  Adh_Dhaariyaat,
  At_Tur,
  An_Najm,
  Al_Qamar,
  Ar_Rahman,
  Al_Waqiah,
  Al_Hadid,
  Al_Mujadilah,
  Al_Hashr,
  Al_Mumtahanah,
  As_Saff,
  Al_Jumuah,
  Al_Munafiqun,
  At_Taghabun,
  At_Talaq,
  At_Tahrim,
  Al_Mulk,
  Al_Qalam,
  Al_Haaqqa,
  Al_Maaarij,
  Nuh,
  Al_Jinn,
  Al_Muzzammil,
  Al_Muddaththir,
  Al_Qiyamah,
  Ad_Dahr,
  Al_Mursalaat,
  An_Naba,
  An_Naaziaat,
  Abasa,
  At_Takwir,
  Al_Infitar,
  Al_Mutaffifin,
  Al_Inshiqaaq,
  Al_Buruj,
  At_Taariq,
  Al_Ala,
  Al_Ghaashiyah,
  Al_Fajr,
  Al_Balad,
  Ash_Shams,
  Al_Layl,
  Ad_Dhuha,
  Ash_Sharh,
  At_Tin,
  Al_Alaq,
  Al_Qadr,
  Al_Bayyinah,
  Az_Zalzalah,
  Al_Aadiyat,
  Al_Qaariah,
  At_Takaathur,
  Al_Asr,
  Al_Humazah,
  Al_Fil,
  Quraish,
  Al_Maaun,
  Al_Kawthar,
  Al_Kaafirun,
  An_Nasr,
  Al_Masad,
  Al_Ikhlas,
  Al_Falaq,
  An_Naas,

  // const S(this.surah);
  // final Surah surah;
}
