import 'package:flutter/src/widgets/framework.dart';
import 'package:hapi/event/et.dart';
import 'package:hapi/main_c.dart'; // needed to get Extension on Enum
import 'package:hapi/quran/quran.dart';
import 'package:hapi/relic/relic.dart';
import 'package:hapi/tarikh/timeline/timeline_data.dart';

class Surah extends Relic {
  Surah({
    required Enum e,
    required this.numEgypt,
    required this.numNoldeke,
    required this.juzBegin,
    this.juzEnd,
    required this.cntVerses,
    required this.cntRuku,
    required this.revelationPlace,
    this.trMuqattaat,
    this.arMuqattaat,
    required this.titleRefersToAya, // TODO translate titleRefersTo
    required this.mainThemes, // TODO translate mainThemes
  }) : super(
          // Relic data:
          e: e,
          // Event data:
          et: ET.Surah,
          tkEra: 'Quran Revelation',
          tkTitle: e.tkIsimA,
          start: 0, // TODO put in quran revelation dates!
          end: 0,
        );
  final int numEgypt;
  final int numNoldeke;
  final int juzBegin;
  final int? juzEnd;
  final int cntVerses;
  final double cntRuku;
  final REVELATION_PLACE revelationPlace;
  final String? trMuqattaat;
  final String? arMuqattaat;
  final Aya titleRefersToAya;
  final List<String> mainThemes;

  bool get isSingleJuz => juzEnd == null;
  bool get isMultiJuz => juzEnd != null;

  bool get isMuqattaat => trMuqattaat != null;

  /// Show Surah number on RelicSetUI()
  @override
  bool get showNum => true;

  @override
  // TODO: implement widget
  Widget get widget => throw UnimplementedError();

  @override
  Asset getAsset({width = 200.0, height = 200.0, scale = 1.0}) => Asset(
        filename: 'images/logo/logo.png', // TODO asdf: implement
        //filename: 'images/surah/${e.name}.png',
        width: width,
        height: height,
        scale: scale,
      );

  static List<Relic> get relics => _relics;
  static List<RelicSetFilter> get relicSetFilters => _relicSetFilters;
}

final List<Surah> _relics = [
  Surah(
    e: S.Al__Fatihah,
    numEgypt: 5,
    numNoldeke: 48,
    juzBegin: 1,
    juzEnd: null,
    cntVerses: 7,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: [
      'The fundamental principles of the Quran in a condensed form.'
    ],
  ),
  Surah(
    e: S.Al__Baqarah,
    numEgypt: 87,
    numNoldeke: 91,
    juzBegin: 1,
    juzEnd: 3,
    cntVerses: 286,
    cntRuku: 40,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(2, 67, end: 73),
    mainThemes: [
      'The necessity of God-consciousness.',
      'The error(s) committed by followers of earlier revelations.',
      'Legal ordinances (ethics, social relations, warfare etc.).',
      'Ibrahim',
      'Kaaba',
      'Ayat Al-Kursi (255).'
    ],
  ),
  Surah(
    e: S.Aali__a_Imran,
    numEgypt: 89,
    numNoldeke: 97,
    juzBegin: 3,
    juzEnd: 4,
    cntVerses: 200,
    cntRuku: 20,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(3, 33, end: 35),
    mainThemes: [
      'The human nature of Isa.',
      'The oneness of Allah.',
      "Man's faith and temptations.",
      'The Battle of Uhud in 3 AH.'
    ],
  ),
  Surah(
    e: S.An__Nisa,
    numEgypt: 92,
    numNoldeke: 100,
    juzBegin: 4,
    juzEnd: 6,
    cntVerses: 176,
    cntRuku: 24,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: [
      'Unity of the human race and the mutual obligations of men and women towards one another (1).',
      'Rights of women.',
      'Questions related to family life (including marriage and inheritance).',
      'Peace and war.',
      'Relations of believers with unbelievers.',
      'Striving in the Cause of Allah/Jihad (95–97).'
    ],
  ),
  Surah(
    e: S.Al__Ma_a_idah,
    numEgypt: 112,
    numNoldeke: 114,
    juzBegin: 6,
    juzEnd: 7,
    cntVerses: 120,
    cntRuku: 16,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(5, 112, end: 114),
    mainThemes: [
      'Religious rites and social obligations.',
      'Corruption of the original message of the Injeel by Jews and Christians (68–77, 116–118).'
    ],
  ),
  Surah(
    e: S.Al__An_a_am,
    numEgypt: 55,
    numNoldeke: 89,
    juzBegin: 7,
    juzEnd: 8,
    cntVerses: 165,
    cntRuku: 20,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(6, 136),
    mainThemes: [
      'Human nature of Muhammad (50).',
      'Oneness and uniqueness of Allah (e.g. 100, 103).',
      'Pre-Islamic superstitions concerning animals (136).'
    ],
  ),
  Surah(
    e: S.Al__A_a_raf,
    numEgypt: 39,
    numNoldeke: 87,
    juzBegin: 8,
    juzEnd: 9,
    cntVerses: 206,
    cntRuku: 24,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Mim-Sad',
    arMuqattaat: 'المص',
    titleRefersToAya: AQ(7, 46, end: 48),
    mainThemes: [
      'The mission of the prophets.',
      'Adam, Hawwa and Iblis (16–25).',
      'Stories of Nuh, Hud, Salih, Lut, Shuáyb and Musa (59–171).',
      "Allah's Covenant with humanity (172).",
      "What happens to those who discard Allah's message (175)."
    ],
  ),
  Surah(
    e: S.Al__Anfal,
    numEgypt: 88,
    numNoldeke: 95,
    juzBegin: 9,
    juzEnd: 10,
    cntVerses: 75,
    cntRuku: 10,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(8, 1),
    mainThemes: [
      'The Battle of Badr in 2 AH.',
      'Doctrine of sacrifice through action.'
    ],
  ),
  Surah(
    e: S.At__Tawbah,
    numEgypt: 113,
    numNoldeke: 113,
    juzBegin: 10,
    juzEnd: 11,
    cntVerses: 129,
    cntRuku: 16,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU(
        'The Surah explains the nature of Tawbah (repentance) and mentions the conditions of its acceptance.'),
    mainThemes: [
      'Problems of war between believers and their enemies.',
      'The expedition to Tabuk in 9 AH.',
      'Prohibition of intercalation in the Islamic lunar calendar (37).',
      'Those who cannot attain to faith (124–127).'
    ],
  ),
  Surah(
    e: S.Yunus,
    numEgypt: 51,
    numNoldeke: 84,
    juzBegin: 11,
    juzEnd: null,
    cntVerses: 109,
    cntRuku: 11,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AQ(10, 98),
    mainThemes: [
      'The revelation of the Quran to Muhammad (15–17, 37–38, 94).',
      'References to earlier prophets.',
      'Fundamental tenets of Islam.'
    ],
  ),
  Surah(
    e: S.Hud,
    numEgypt: 52,
    numNoldeke: 75,
    juzBegin: 11,
    juzEnd: 12,
    cntVerses: 123,
    cntRuku: 10,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AQ(11, 50, end: 60),
    mainThemes: [
      "The revelation of God's will through his prophets.",
      'More stories of earlier prophets.',
      'Just dealings between men.'
    ],
  ),
  Surah(
    e: S.Yusuf,
    numEgypt: 53,
    numNoldeke: 77,
    juzBegin: 12,
    juzEnd: 13,
    cntVerses: 111,
    cntRuku: 12,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: [
      "The story of the prophet Joseph (as an illustration of God's unfathomable direction of men's affairs)."
    ],
  ),
  Surah(
    e: S.Ar__Ra_a_d,
    numEgypt: 96,
    numNoldeke: 90,
    juzBegin: 13,
    juzEnd: null,
    cntVerses: 43,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: 'Alif-Lam-Mim-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AQ(13, 13),
    mainThemes: [
      "God's revelation, through his prophets, of certain fundamental moral truths, and the consequences of accepting or rejecting them."
    ],
  ),
  Surah(
    e: S.Ibrahim,
    numEgypt: 72,
    numNoldeke: 76,
    juzBegin: 13,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 7,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AQ(14, 35, end: 41),
    mainThemes: [
      "The revelation of God's word to all mankind, destined to lead man from darkness to light."
    ],
  ),
  Surah(
    e: S.Al__Hijr,
    numEgypt: 54,
    numNoldeke: 57,
    juzBegin: 14,
    juzEnd: null,
    cntVerses: 99,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Ra',
    arMuqattaat: 'الر',
    titleRefersToAya: AQ(15, 80),
    mainThemes: [
      "God's guidance to man through revelation of the Quran, which will remain uncorrupted for all times (9)."
    ],
  ),
  Surah(
    e: S.An__Nahl,
    numEgypt: 70,
    numNoldeke: 73,
    juzBegin: 14,
    juzEnd: null,
    cntVerses: 128,
    cntRuku: 16,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(16, 68, end: 69),
    mainThemes: [
      "God's creativeness:Manifested in the instincts of the bee.",
      'Culmination: Guidance through his revealed word.'
    ],
  ),
  Surah(
    e: S.Al__Isra,
    numEgypt: 50,
    numNoldeke: 67,
    juzBegin: 15,
    juzEnd: null,
    cntVerses: 111,
    cntRuku: 12,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(17, 1),
    mainThemes: [
      "Muhammad's Night journey from Mecca to Jerusalem.",
      'The children of Israel (2–8, 101–104).'
    ],
  ),
  Surah(
    e: S.Al__Kahf,
    numEgypt: 69,
    numNoldeke: 69,
    juzBegin: 15,
    juzEnd: 16,
    cntVerses: 110,
    cntRuku: 12,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(18, 13, end: 20),
    mainThemes: [
      'A series of parables or allegories on the theme of faith in God versus excessive attachment to the life of this world. Including:The men of the cave (13–20).',
      'The rich man and the poor man (32–44).',
      'Moses and the unnamed sage (60–82).',
      'The allegory of ‘Dhu’l-Qarnayn, the Two-Horned One’ (83–98).'
    ],
  ),
  Surah(
    e: S.Maryam,
    numEgypt: 44,
    numNoldeke: 58,
    juzBegin: 16,
    juzEnd: null,
    cntVerses: 98,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: "Kaf-Ha-Ya-'Ayn-Sad",
    arMuqattaat: 'كهيعص',
    titleRefersToAya: AQ(19, 16, end: 37),
    mainThemes: [
      'The story of Zachariah and his son John, the precursor of Jesus (2–15).',
      'The story of Mary and Jesus (16–37).'
    ],
  ),
  Surah(
    e: S.Ta__Ha,
    numEgypt: 45,
    numNoldeke: 55,
    juzBegin: 16,
    juzEnd: null,
    cntVerses: 135,
    cntRuku: 8,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ta-Ha',
    arMuqattaat: 'طه',
    titleRefersToAya: AQ(20, 1),
    mainThemes: [
      'The guidance offered by God through his prophets.',
      'The fundamental truths inherent in all revealed religions are identical.The story of Moses (9-98).'
    ],
  ),
  Surah(
    e: S.Al__Anbiya,
    numEgypt: 73,
    numNoldeke: 65,
    juzBegin: 17,
    juzEnd: null,
    cntVerses: 112,
    cntRuku: 7,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(21, 48, end: 91),
    mainThemes: [
      'The oneness, uniqueness and transcendence of God.',
      'The continuity and intrinsic unity of all divine revelation.Stories of the prophets of old (48–91).',
      'The believers of all faiths belong to one single community (92).'
    ],
  ),
  Surah(
    e: S.Al__Hajj,
    numEgypt: 103,
    numNoldeke: 107,
    juzBegin: 17,
    juzEnd: null,
    cntVerses: 78,
    cntRuku: 10,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(22, 25, end: 38),
    mainThemes: [
      'The Mecca pilgrimage and some of the rituals connected with it (25–38).'
    ],
  ),
  Surah(
    e: S.Al__Mu_a_minun,
    numEgypt: 74,
    numNoldeke: 64,
    juzBegin: 18,
    juzEnd: null,
    cntVerses: 118,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(23, 1),
    mainThemes: [
      'True faith.',
      "The evidence of the existence of an almighty Creator, and man's ultimate responsibility before Him.",
      "The unity of all religious communities, broken by man's egotism, greed and striving after power (52–53).",
      'The impossibility to believe in God, without believing in life after death.'
    ],
  ),
  Surah(
    e: S.An__Nur,
    numEgypt: 102,
    numNoldeke: 105,
    juzBegin: 18,
    juzEnd: null,
    cntVerses: 64,
    cntRuku: 9,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(24, 35),
    mainThemes: [
      'Mutual relations and ethical rules between men and women.',
      'The mystic parable of the ‘light of God’ ("Verse of Light") (35).'
    ],
  ),
  Surah(
    e: S.Al__Furqan,
    numEgypt: 42,
    numNoldeke: 66,
    juzBegin: 18,
    juzEnd: 19,
    cntVerses: 77,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(25, 1),
    mainThemes: [
      'The purpose of every divine revelation is to provide a stable criterion of true and false.',
      'The humanness of every apostle sent by God to man (20).',
      "Divine revelation belongs to God's creative activity."
    ],
  ),
  Surah(
    e: S.Ash__Shu_a_ara,
    numEgypt: 47,
    numNoldeke: 56,
    juzBegin: 19,
    juzEnd: null,
    cntVerses: 227,
    cntRuku: 11,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ta-Sin-Mim',
    arMuqattaat: 'طسم',
    titleRefersToAya: AQ(26, 224),
    mainThemes: [
      "Man's weakness, which causes him to reject God's message and worship power and wealth etc."
    ],
  ),
  Surah(
    e: S.An__Naml,
    numEgypt: 48,
    numNoldeke: 68,
    juzBegin: 19,
    juzEnd: 20,
    cntVerses: 93,
    cntRuku: 7,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ta-Sin',
    arMuqattaat: 'طس',
    titleRefersToAya: AQ(27, 18),
    mainThemes: ['The legend of king Solomon and queen of Sheba.'],
  ),
  Surah(
    e: S.Al__Qasas,
    numEgypt: 49,
    numNoldeke: 79,
    juzBegin: 20,
    juzEnd: null,
    cntVerses: 88,
    cntRuku: 9,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ta-Sin-Mim',
    arMuqattaat: 'طسم',
    titleRefersToAya: AQ(28, 25),
    mainThemes: ['Human aspects of the life of Moses.'],
  ),
  Surah(
    e: S.Al__Ankabut,
    numEgypt: 85,
    numNoldeke: 81,
    juzBegin: 20,
    juzEnd: 21,
    cntVerses: 69,
    cntRuku: 7,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(29, 41),
    mainThemes: [
      'The parable of ‘the spider house’, a symbol of false beliefs that are destined to be blown away by the winds of truth (41).'
    ],
  ),
  Surah(
    e: S.Ar__Rum,
    numEgypt: 84,
    numNoldeke: 74,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 60,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(30, 1),
    mainThemes: [
      'Predictions of the near victory of the Byzantines over the Persians and the Battle of Badr in 2 AH (1–7).',
      "God's ability to resurrect the dead at the end of time, and the people's ignorance of this."
    ],
  ),
  Surah(
    e: S.Luqmaan,
    numEgypt: 57,
    numNoldeke: 82,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 34,
    cntRuku: 4,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(31, 12, end: 19),
    mainThemes: [
      'The story of Luqman, a legendary sage, counselling his son (12–19).'
    ],
  ),
  Surah(
    e: S.As__Sajdah,
    numEgypt: 75,
    numNoldeke: 70,
    juzBegin: 21,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 3,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Alif-Lam-Mim',
    arMuqattaat: 'الم',
    titleRefersToAya: AQ(32, 15),
    mainThemes: [
      "God's creation.",
      "God's revelation and man's acceptance or denial.",
      'The Day of Judgement.'
    ],
  ),
  Surah(
    e: S.Al__Ahzaab,
    numEgypt: 90,
    numNoldeke: 103,
    juzBegin: 21,
    juzEnd: 22,
    cntVerses: 73,
    cntRuku: 9,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(33, 9, end: 27),
    mainThemes: [
      'The War of the Confederates in 5  (9-27).',
      'The relationship between Muhammad and his family.'
    ],
  ),
  Surah(
    e: S.Saba,
    numEgypt: 58,
    numNoldeke: 85,
    juzBegin: 22,
    juzEnd: null,
    cntVerses: 54,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(34, 15, end: 20),
    mainThemes: [
      'The insignificance of the knowledge accessible to man (9).',
      'The story of the people of Sheba, as an example of the impermanence of human power, wealth and glory (15–20).',
      'Always be conscious of God (46).'
    ],
  ),
  Surah(
    e: S.Faatir,
    numEgypt: 43,
    numNoldeke: 86,
    juzBegin: 22,
    juzEnd: null,
    cntVerses: 45,
    cntRuku: 5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(35, 1),
    mainThemes: [
      "God's power to create and resurrect.",
      "God's revelation of his will through his prophets."
    ],
  ),
  Surah(
    e: S.Ya__Sin,
    numEgypt: 41,
    numNoldeke: 60,
    juzBegin: 22,
    juzEnd: 23,
    cntVerses: 83,
    cntRuku: 5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ya-Sin',
    arMuqattaat: 'يس',
    titleRefersToAya: AQ(36, 1),
    mainThemes: [
      "Man's moral responsibility, resurrection and God's judgment.",
      'To be recited over the dying and in the prayers of the dead.'
    ],
  ),
  Surah(
    e: S.As__Saaffaat,
    numEgypt: 56,
    numNoldeke: 50,
    juzBegin: 23,
    juzEnd: null,
    cntVerses: 182,
    cntRuku: 5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(37, 1),
    mainThemes: [
      'Resurrection and the certainty that all human beings will have to answer before God.',
      "Man's constant need of prophetic guidance.Stories of earlier prophets (75–148)."
    ],
  ),
  Surah(
    e: S.Saad,
    numEgypt: 38,
    numNoldeke: 59,
    juzBegin: 23,
    juzEnd: null,
    cntVerses: 88,
    cntRuku: 5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Saad',
    arMuqattaat: 'ص',
    titleRefersToAya: AQ(38, 1),
    mainThemes: [
      'Divine guidance and its rejection by those who are lost in fast pride.'
    ],
  ),
  Surah(
    e: S.Az__Zumar,
    numEgypt: 59,
    numNoldeke: 80,
    juzBegin: 23,
    juzEnd: 24,
    cntVerses: 75,
    cntRuku: 8,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(39, 71, end: 73),
    mainThemes: [
      'The evidence of the existence and oneness of God in all manifestations of nature.',
      'God forgives all sins to him who repents before his death.',
      'Allegories of the Last Hour and the Day of Judgment.'
    ],
  ),
  Surah(
    e: S.Ghafir,
    numEgypt: 60,
    numNoldeke: 78,
    juzBegin: 24,
    juzEnd: null,
    cntVerses: 85,
    cntRuku: 9,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(40, 3),
    mainThemes: [
      "Man's false pride, worship of false values (wealth, power etc.) and his denial of divine guidance.Stories of earlier prophets."
    ],
  ),
  Surah(
    e: S.Fussilat,
    numEgypt: 61,
    numNoldeke: 71,
    juzBegin: 24,
    juzEnd: 25,
    cntVerses: 54,
    cntRuku: 6,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(41, 3),
    mainThemes: ["Man's acceptance or rejection of divine revelation."],
  ),
  Surah(
    e: S.Ash__Shura,
    numEgypt: 62,
    numNoldeke: 83,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 53,
    cntRuku: 5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: "Ha-Mim-'Ayn-Sin-Qaf",
    arMuqattaat: 'حم عسق',
    titleRefersToAya: AQ(42, 36),
    mainThemes: [
      'God is undefinable and unfathomable (11, 16).',
      'All prophets taught the oneness of God, so all believers of all ‘denominations’ should see themselves as ‘one single community’ (13, 15).',
      'The law of cause and effect: In the life to come man will only harvest ‘what his own hands have wrought’ in this world.'
    ],
  ),
  Surah(
    e: S.Az__Zukhruf,
    numEgypt: 63,
    numNoldeke: 61,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 89,
    cntRuku: 7,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(43, 35),
    mainThemes: [
      'To equal anyone or anything with God is sprititually destructive and logically unacceptable.',
      "People's blind adherence to the faith of their forefathers (22–23)."
    ],
  ),
  Surah(
    e: S.Ad__Dukhaan,
    numEgypt: 64,
    numNoldeke: 53,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 59,
    cntRuku: 3,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(44, 10),
    mainThemes: [
      'Through revelation worldly pride is eventually brought to naught.'
    ],
  ),
  Surah(
    e: S.Al__Jaathiyah,
    numEgypt: 65,
    numNoldeke: 72,
    juzBegin: 25,
    juzEnd: null,
    cntVerses: 37,
    cntRuku: 4,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(45, 28),
    mainThemes: [
      'The humility with which all human beings will face their final judgment on resurrection (28).'
    ],
  ),
  Surah(
    e: S.Al__Ahqaaf,
    numEgypt: 66,
    numNoldeke: 88,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 35,
    cntRuku: 4.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Ha-Mim',
    arMuqattaat: 'حم',
    titleRefersToAya: AQ(46, 21),
    mainThemes: [
      'Warning the disbelievers of their miserable fate, and reassuring the believers of their salvation.'
    ],
  ),
  Surah(
    e: S.Muhammad,
    numEgypt: 95,
    numNoldeke: 96,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 38,
    cntRuku: 4,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(47, 2),
    mainThemes: [
      "Fighting (qital) in God's cause.",
      'Instructions for Muslims to be virtuous to their parents.',
      'The Story of Hud and the punishment of that befell his people.',
      'Advising Muhammad to be more patient in delivering Islam'
    ],
  ),
  Surah(
    e: S.Al__Fath,
    numEgypt: 111,
    numNoldeke: 108,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 4.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(48, 1),
    mainThemes: ['The Truce of Hudaybiyyah in 6 AH.'],
  ),
  Surah(
    e: S.Al__Hujuraat,
    numEgypt: 106,
    numNoldeke: 112,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 18,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(49, 4),
    mainThemes: [
      'Social ethics.Reverence to Muhammad and the righteous leaders after him.',
      'The brotherhood of all believers and all mankind (10, 13).',
      'The difference between true faith and outward observance of religious formalities (14).'
    ],
  ),
  Surah(
    e: S.Qaaf,
    numEgypt: 34,
    numNoldeke: 54,
    juzBegin: 26,
    juzEnd: null,
    cntVerses: 45,
    cntRuku: 3,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Qaf',
    arMuqattaat: 'ق',
    titleRefersToAya: AQ(50, 1),
    mainThemes: [
      'Death and resurrection.',
      'God is closer to man than his neck-vein (16).'
    ],
  ),
  Surah(
    e: S.Adh__Dhaariyaat,
    numEgypt: 67,
    numNoldeke: 39,
    juzBegin: 26,
    juzEnd: 27,
    cntVerses: 60,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(51, 1),
    mainThemes: [
      'Destruction of those who denied the messengers, and a warning for those who deny the truth.'
    ],
  ),
  Surah(
    e: S.At__Tur,
    numEgypt: 76,
    numNoldeke: 40,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 49,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(52, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.An__Najm,
    numEgypt: 23,
    numNoldeke: 28,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 62,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(53, 1),
    mainThemes: [
      "Muhammad's ascension to heaven in Al-Isra' wal-Mi'raaj (13–18)."
    ],
  ),
  Surah(
    e: S.Al__Qamar,
    numEgypt: 37,
    numNoldeke: 49,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 55,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(54, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Ar__Rahman,
    numEgypt: 97,
    numNoldeke: 43,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 78,
    cntRuku: 3,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(55, 1),
    mainThemes: [
      'Everything will pass away, except the face of God (26–27).',
      'Description of paradise (46–78).'
    ],
  ),
  Surah(
    e: S.Al__Waqi_a_ah,
    numEgypt: 46,
    numNoldeke: 41,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 96,
    cntRuku: 3.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(56, 1),
    mainThemes: [
      'Description of life in the Hereafter for the believers and disbelievers.'
    ],
  ),
  Surah(
    e: S.Al__Hadid,
    numEgypt: 94,
    numNoldeke: 99,
    juzBegin: 27,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 4,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(57, 25),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Mujadilah,
    numEgypt: 105,
    numNoldeke: 106,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 22,
    cntRuku: 3.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(58, 1),
    mainThemes: [
      'Divorce.',
      'Faith and denial.',
      'Hypocrisy.',
      'The attitude believers should have toward non-believers.'
    ],
  ),
  Surah(
    e: S.Al__Hashr,
    numEgypt: 101,
    numNoldeke: 102,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 24,
    cntRuku: 3.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(59, 2),
    mainThemes: [
      'The conflict between the Muslim community and the Jewish tribe of Banu’n-Nadir of Medina.'
    ],
  ),
  Surah(
    e: S.Al__Mumtahanah,
    numEgypt: 91,
    numNoldeke: 110,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 13,
    cntRuku: 2.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(60, 10),
    mainThemes: ['The believers’ relations with unbelievers.'],
  ),
  Surah(
    e: S.As__Saff,
    numEgypt: 109,
    numNoldeke: 98,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 14,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(61, 4),
    mainThemes: [
      'A call to unity between professed belief and actual behaviour.'
    ],
  ),
  Surah(
    e: S.Al__Jumu_a_ah,
    numEgypt: 110,
    numNoldeke: 94,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(62, 9, end: 10),
    mainThemes: ['Obligatory congregational prayer on Friday.'],
  ),
  Surah(
    e: S.Al__Munafiqun,
    numEgypt: 104,
    numNoldeke: 104,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: ['Hypocrisy.'],
  ),
  Surah(
    e: S.At__Taghabun,
    numEgypt: 108,
    numNoldeke: 93,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 18,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(64, 9),
    mainThemes: [''],
  ),
  Surah(
    e: S.At__Talaq,
    numEgypt: 99,
    numNoldeke: 101,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 12,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: ['Divorce (waiting period, remarriage).'],
  ),
  Surah(
    e: S.At__Tahrim,
    numEgypt: 107,
    numNoldeke: 109,
    juzBegin: 28,
    juzEnd: null,
    cntVerses: 12,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(66, 1),
    mainThemes: ["Certain aspects of Muhammad's personal and family life."],
  ),
  Surah(
    e: S.Al__Mulk,
    numEgypt: 77,
    numNoldeke: 63,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(67, 1),
    mainThemes: [
      "Man's inability to understand the mysteries of the universe, and his dependence on guidance through divine revelation.",
      "The manifestation of God's absolute perfection in creation through the fine tuning of the universe."
    ],
  ),
  Surah(
    e: S.Al__Qalam,
    numEgypt: 2,
    numNoldeke: 18,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: 'Nun',
    arMuqattaat: 'ن',
    titleRefersToAya: AQ(68, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Haaqqa,
    numEgypt: 78,
    numNoldeke: 38,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 52,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(69, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Ma_a_aarij,
    numEgypt: 79,
    numNoldeke: 42,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 44,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(70, 3),
    mainThemes: [
      'The unwillingness to believe, caused by the restlessness inherent in human nature.'
    ],
  ),
  Surah(
    e: S.Nuh,
    numEgypt: 71,
    numNoldeke: 51,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 28,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: [
      'The story of Noah.The struggle against blind materialism and the lack of spiritual values.'
    ],
  ),
  Surah(
    e: S.Al__Jinn,
    numEgypt: 40,
    numNoldeke: 62,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 28,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(72, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Muzzammil,
    numEgypt: 3,
    numNoldeke: 23,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 20,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(73, 1),
    mainThemes: ['Loosening the strict regulation on night prayer.'],
  ),
  Surah(
    e: S.Al__Muddaththir,
    numEgypt: 4,
    numNoldeke: 2,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 56,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(74, 1),
    mainThemes: [
      'This short early surah outlines almost all fundamental Quranic concepts.',
      "God's promise of eternal damnation for the disbelievers."
    ],
  ),
  Surah(
    e: S.Al__Qiyamah,
    numEgypt: 31,
    numNoldeke: 36,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 40,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(75, 1),
    mainThemes: ['The concept of resurrection.'],
  ),
  Surah(
    e: S.Ad__Dahr,
    numEgypt: 98,
    numNoldeke: 52,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 31,
    cntRuku: 2,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(76, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Mursalaat,
    numEgypt: 33,
    numNoldeke: 32,
    juzBegin: 29,
    juzEnd: null,
    cntVerses: 50,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(77, 1),
    mainThemes: ['The gradual revelation of the Quran.'],
  ),
  Surah(
    e: S.An__Naba_a_,
    numEgypt: 80,
    numNoldeke: 33,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 40,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(78, 2),
    mainThemes: [
      'Life after death.',
      "Resurrection and God's ultimate judgment."
    ],
  ),
  Surah(
    e: S.An__Naazi_a_aat,
    numEgypt: 81,
    numNoldeke: 31,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 46,
    cntRuku: 1.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(79, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Abasa,
    numEgypt: 24,
    numNoldeke: 17,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 42,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(80, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.At__Takwir,
    numEgypt: 7,
    numNoldeke: 27,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 29,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(81, 1),
    mainThemes: ["The Last Hour and man's resurrection."],
  ),
  Surah(
    e: S.Al__Infitar,
    numEgypt: 82,
    numNoldeke: 26,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(82, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Mutaffifin,
    numEgypt: 86,
    numNoldeke: 37,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 36,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(83, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Inshiqaaq,
    numEgypt: 83,
    numNoldeke: 29,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 25,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(84, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Buruj,
    numEgypt: 27,
    numNoldeke: 22,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 22,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(85, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.At__Taariq,
    numEgypt: 36,
    numNoldeke: 15,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 17,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(86, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__A_a_la,
    numEgypt: 8,
    numNoldeke: 19,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(87, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Ghaashiyah,
    numEgypt: 68,
    numNoldeke: 34,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 26,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(88, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Fajr,
    numEgypt: 10,
    numNoldeke: 35,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 30,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(89, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Balad,
    numEgypt: 35,
    numNoldeke: 11,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 20,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(90, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Ash__Shams,
    numEgypt: 26,
    numNoldeke: 16,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 15,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(91, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Layl,
    numEgypt: 9,
    numNoldeke: 10,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 21,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(92, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Ad__Dhuha,
    numEgypt: 11,
    numNoldeke: 13,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(93, 1),
    mainThemes: [
      "Man's suffering and God's justice.",
      "A message of hope and consolation is given to man from Allah's past mercies.",
      'Man is bidden to pursue the path of goodness and proclaim the bounties of Allah.',
      'Prophecy regarding the good future for Muhammad.'
    ],
  ),
  Surah(
    e: S.Ash__Sharh,
    numEgypt: 12,
    numNoldeke: 12,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(94, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.At__Tin,
    numEgypt: 28,
    numNoldeke: 20,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(95, 1),
    mainThemes: [
      'A fundamental moral verity, common to all true religious teachings.'
    ],
  ),
  Surah(
    e: S.Al__Alaq,
    numEgypt: 1,
    numNoldeke: 1,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 19,
    cntRuku: 0.5,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(96, 2),
    mainThemes: ['The first five verses revealed to Muhammad (1–5).'],
  ),
  Surah(
    e: S.Al__Qadr,
    numEgypt: 25,
    numNoldeke: 14,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(97, 1),
    mainThemes: ['The Night of Laylat-ul-Qadr'],
  ),
  Surah(
    e: S.Al__Bayyinah,
    numEgypt: 100,
    numNoldeke: 92,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 1,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(98, 1),
    mainThemes: ['The Evidence, and the clear truth'],
  ),
  Surah(
    e: S.Az__Zalzalah,
    numEgypt: 93,
    numNoldeke: 25,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(99, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al___a_Aadiyat,
    numEgypt: 14,
    numNoldeke: 30,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(100, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Qaari_a_ah,
    numEgypt: 30,
    numNoldeke: 24,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 11,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(101, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.At__Takaathur,
    numEgypt: 16,
    numNoldeke: 8,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 8,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(102, 1),
    mainThemes: ["Man's greed and tendencies."],
  ),
  Surah(
    e: S.Al___a_Asr,
    numEgypt: 13,
    numNoldeke: 21,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(103, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Humazah,
    numEgypt: 32,
    numNoldeke: 6,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 9,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(104, 1),
    mainThemes: [''],
  ),
  Surah(
    e: S.Al__Fil,
    numEgypt: 19,
    numNoldeke: 9,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(105, 1),
    mainThemes: [
      'The Abyssinian attack against Mecca in the year 570 CE, the Year of the Elephant.'
    ],
  ),
  Surah(
    e: S.Quraish,
    numEgypt: 29,
    numNoldeke: 4,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 4,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(106, 1),
    mainThemes: [
      'The Quraysh, custodians of the Kaaba, should be thankful to God for protecting them from hunger and danger.'
    ],
  ),
  Surah(
    e: S.Al__Maa_a_un,
    numEgypt: 17,
    numNoldeke: 7,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 7,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(107, 7),
    mainThemes: [
      'The meaning of true worship through sincere devotion and helping those in need.'
    ],
  ),
  Surah(
    e: S.Al__Kawthar,
    numEgypt: 15,
    numNoldeke: 5,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(108, 1),
    mainThemes: [
      'Spiritual riches through devotion and sacrifice.',
      'Hatred results in the cutting off of all hope.'
    ],
  ),
  Surah(
    e: S.Al__Kaafirun,
    numEgypt: 18,
    numNoldeke: 45,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 6,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(109, 1),
    mainThemes: ['The correct attitude towards those who reject faith.'],
  ),
  Surah(
    e: S.An__Nasr,
    numEgypt: 114,
    numNoldeke: 111,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 3,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Madinah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(110, 1),
    mainThemes: ["The last complete surah revealed before Muhammad's death."],
  ),
  Surah(
    e: S.Al__Masad,
    numEgypt: 6,
    numNoldeke: 3,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(111, 5),
    mainThemes: [
      "Allah cursing Abu Lahab and his wife, who was Muhammad's uncle and at the time of the revelation of this verse, Muhammad's brother in law, due to his hostility towards Islam and Prophet Muhammad."
    ],
  ),
  Surah(
    e: S.Al__Ikhlas,
    numEgypt: 22,
    numNoldeke: 44,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 4,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: ['The oneness of God.'],
  ),
  Surah(
    e: S.Al__Falaq,
    numEgypt: 20,
    numNoldeke: 46,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 5,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AQ(113, 1),
    mainThemes: ['Seek refuge in God from evil of others.'],
  ),
  Surah(
    e: S.An__Naas,
    numEgypt: 21,
    numNoldeke: 47,
    juzBegin: 30,
    juzEnd: null,
    cntVerses: 6,
    cntRuku: 0.333,
    revelationPlace: REVELATION_PLACE.Makkah,
    trMuqattaat: null,
    arMuqattaat: null,
    titleRefersToAya: AU('Whole Surah'),
    mainThemes: ["Trust in God's protection from temptations."],
  ),
];

const List<int> _relicOrder = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
  41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
  60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
  79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
  98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
  113, //
];

final List<RelicSetFilter> _relicSetFilters = [
  const RelicSetFilter(
    tkLabel: 'Order by Quran',
    idxList: _relicOrder,
    tprMax: 38, // 38 = 114/3
  ),
  RelicSetFilter(
    tkLabel: 'Order by Egyptian Standard',
    field: FILTER_FIELD.OrderByEgyptianStandard,
    idxList: [
      S.Al__Alaq.index, S.Al__Qalam.index, S.Al__Muzzammil.index,
      S.Al__Muddaththir.index, S.Al__Fatihah.index, S.Al__Masad.index,
      S.At__Takwir.index, S.Al__A_a_la.index, S.Al__Layl.index,
      S.Al__Fajr.index, S.Ad__Dhuha.index, S.Ash__Sharh.index,
      S.Al___a_Asr.index, S.Al___a_Aadiyat.index, S.Al__Kawthar.index,
      S.At__Takaathur.index, S.Al__Maa_a_un.index, S.Al__Kaafirun.index,
      S.Al__Fil.index, S.Al__Falaq.index, S.An__Naas.index, S.Al__Ikhlas.index,
      S.An__Najm.index, S.Abasa.index, S.Al__Qadr.index, S.Ash__Shams.index,
      S.Al__Buruj.index, S.At__Tin.index, S.Quraish.index,
      S.Al__Qaari_a_ah.index, S.Al__Qiyamah.index, S.Al__Humazah.index,
      S.Al__Mursalaat.index, S.Qaaf.index, S.Al__Balad.index,
      S.At__Taariq.index, S.Al__Qamar.index, S.Saad.index, S.Al__A_a_raf.index,
      S.Al__Jinn.index, S.Ya__Sin.index, S.Al__Furqan.index, S.Faatir.index,
      S.Maryam.index, S.Ta__Ha.index, S.Al__Waqi_a_ah.index,
      S.Ash__Shu_a_ara.index, S.An__Naml.index, S.Al__Qasas.index,
      S.Al__Isra.index, S.Yunus.index, S.Hud.index, S.Yusuf.index,
      S.Al__Hijr.index, S.Al__An_a_am.index, S.As__Saaffaat.index,
      S.Luqmaan.index, S.Saba.index, S.Az__Zumar.index, S.Ghafir.index,
      S.Fussilat.index, S.Ash__Shura.index, S.Az__Zukhruf.index,
      S.Ad__Dukhaan.index, S.Al__Jaathiyah.index, S.Al__Ahqaaf.index,
      S.Adh__Dhaariyaat.index, S.Al__Ghaashiyah.index, S.Al__Kahf.index,
      S.An__Nahl.index, S.Nuh.index, S.Ibrahim.index, S.Al__Anbiya.index,
      S.Al__Mu_a_minun.index, S.As__Sajdah.index, S.At__Tur.index,
      S.Al__Mulk.index, S.Al__Haaqqa.index, S.Al__Ma_a_aarij.index,
      S.An__Naba_a_.index, S.An__Naazi_a_aat.index, S.Al__Infitar.index,
      S.Al__Inshiqaaq.index, S.Ar__Rum.index, S.Al__Ankabut.index,
      S.Al__Mutaffifin.index, S.Al__Baqarah.index, S.Al__Anfal.index,
      S.Aali__a_Imran.index, S.Al__Ahzaab.index, S.Al__Mumtahanah.index,
      S.An__Nisa.index, S.Az__Zalzalah.index, S.Al__Hadid.index,
      S.Muhammad.index, S.Ar__Ra_a_d.index, S.Ar__Rahman.index,
      S.Ad__Dahr.index, S.At__Talaq.index, S.Al__Bayyinah.index,
      S.Al__Hashr.index, S.An__Nur.index, S.Al__Hajj.index,
      S.Al__Munafiqun.index, S.Al__Mujadilah.index, S.Al__Hujuraat.index,
      S.At__Tahrim.index, S.At__Taghabun.index, S.As__Saff.index,
      S.Al__Jumu_a_ah.index, S.Al__Fath.index, S.Al__Ma_a_idah.index,
      S.At__Tawbah.index, S.An__Nasr.index, //
    ],
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: 'Order by Nöldeke',
    field: FILTER_FIELD.OrderByNoldeke,
    idxList: [
      S.Al__Alaq.index, S.Al__Muddaththir.index, S.Al__Masad.index,
      S.Quraish.index, S.Al__Kawthar.index, S.Al__Humazah.index,
      S.Al__Maa_a_un.index, S.At__Takaathur.index, S.Al__Fil.index,
      S.Al__Layl.index, S.Al__Balad.index, S.Ash__Sharh.index,
      S.Ad__Dhuha.index, S.Al__Qadr.index, S.At__Taariq.index,
      S.Ash__Shams.index, S.Abasa.index, S.Al__Qalam.index, S.Al__A_a_la.index,
      S.At__Tin.index, S.Al___a_Asr.index, S.Al__Buruj.index,
      S.Al__Muzzammil.index, S.Al__Qaari_a_ah.index, S.Az__Zalzalah.index,
      S.Al__Infitar.index, S.At__Takwir.index, S.An__Najm.index,
      S.Al__Inshiqaaq.index, S.Al___a_Aadiyat.index, S.An__Naazi_a_aat.index,
      S.Al__Mursalaat.index, S.An__Naba_a_.index, S.Al__Ghaashiyah.index,
      S.Al__Fajr.index, S.Al__Qiyamah.index, S.Al__Mutaffifin.index,
      S.Al__Haaqqa.index, S.Adh__Dhaariyaat.index, S.At__Tur.index,
      S.Al__Waqi_a_ah.index, S.Al__Ma_a_aarij.index, S.Ar__Rahman.index,
      S.Al__Ikhlas.index, S.Al__Kaafirun.index, S.Al__Falaq.index,
      S.An__Naas.index, S.Al__Fatihah.index, S.Al__Qamar.index,
      S.As__Saaffaat.index, S.Nuh.index, S.Ad__Dahr.index, S.Ad__Dukhaan.index,
      S.Qaaf.index, S.Ta__Ha.index, S.Ash__Shu_a_ara.index, S.Al__Hijr.index,
      S.Maryam.index, S.Saad.index, S.Ya__Sin.index, S.Az__Zukhruf.index,
      S.Al__Jinn.index, S.Al__Mulk.index, S.Al__Mu_a_minun.index,
      S.Al__Anbiya.index, S.Al__Furqan.index, S.Al__Isra.index,
      S.An__Naml.index, S.Al__Kahf.index, S.As__Sajdah.index, S.Fussilat.index,
      S.Al__Jaathiyah.index, S.An__Nahl.index, S.Ar__Rum.index, S.Hud.index,
      S.Ibrahim.index, S.Yusuf.index, S.Ghafir.index, S.Al__Qasas.index,
      S.Az__Zumar.index, S.Al__Ankabut.index, S.Luqmaan.index,
      S.Ash__Shura.index, S.Yunus.index, S.Saba.index, S.Faatir.index,
      S.Al__A_a_raf.index, S.Al__Ahqaaf.index, S.Al__An_a_am.index,
      S.Ar__Ra_a_d.index, S.Al__Baqarah.index, S.Al__Bayyinah.index,
      S.At__Taghabun.index, S.Al__Jumu_a_ah.index, S.Al__Anfal.index,
      S.Muhammad.index, S.Aali__a_Imran.index, S.As__Saff.index,
      S.Al__Hadid.index, S.An__Nisa.index, S.At__Talaq.index, S.Al__Hashr.index,
      S.Al__Ahzaab.index, S.Al__Munafiqun.index, S.An__Nur.index,
      S.Al__Mujadilah.index, S.Al__Hajj.index, S.Al__Fath.index,
      S.At__Tahrim.index, S.Al__Mumtahanah.index, S.An__Nasr.index,
      S.Al__Hujuraat.index, S.At__Tawbah.index, S.Al__Ma_a_idah.index, //
    ],
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: 'Order by Verse Count',
    field: FILTER_FIELD.OrderByVerseCount,
    idxList: [
      S.Al__Baqarah.index, S.Ash__Shu_a_ara.index, S.Al__A_a_raf.index,
      S.Aali__a_Imran.index, S.As__Saaffaat.index, S.An__Nisa.index,
      S.Al__An_a_am.index, S.Ta__Ha.index, S.At__Tawbah.index, S.An__Nahl.index,
      S.Hud.index, S.Al__Ma_a_idah.index, S.Al__Mu_a_minun.index,
      S.Al__Anbiya.index, S.Yusuf.index, S.Al__Isra.index, S.Al__Kahf.index,
      S.Yunus.index, S.Al__Hijr.index, S.Maryam.index, S.Al__Waqi_a_ah.index,
      S.An__Naml.index, S.Az__Zukhruf.index, S.Saad.index, S.Al__Qasas.index,
      S.Ghafir.index, S.Ya__Sin.index, S.Ar__Rahman.index, S.Al__Hajj.index,
      S.Al__Furqan.index, S.Al__Anfal.index, S.Az__Zumar.index,
      S.Al__Ahzaab.index, S.Al__Ankabut.index, S.An__Nur.index,
      S.An__Najm.index, S.Adh__Dhaariyaat.index, S.Ar__Rum.index,
      S.Ad__Dukhaan.index, S.Al__Muddaththir.index, S.Al__Qamar.index,
      S.Saba.index, S.Fussilat.index, S.Ash__Shura.index, S.Al__Haaqqa.index,
      S.Al__Qalam.index, S.Ibrahim.index, S.Al__Mursalaat.index,
      S.At__Tur.index, S.An__Naazi_a_aat.index, S.Faatir.index, S.Qaaf.index,
      S.Al__Ma_a_aarij.index, S.Ar__Ra_a_d.index, S.Abasa.index,
      S.An__Naba_a_.index, S.Al__Qiyamah.index, S.Muhammad.index,
      S.Al__Jaathiyah.index, S.Al__Mutaffifin.index, S.Al__Ahqaaf.index,
      S.Luqmaan.index, S.Ad__Dahr.index, S.Al__Mulk.index, S.As__Sajdah.index,
      S.Al__Fajr.index, S.At__Takwir.index, S.Al__Fath.index, S.Al__Hadid.index,
      S.Al__Jinn.index, S.Nuh.index, S.Al__Ghaashiyah.index,
      S.Al__Inshiqaaq.index, S.Al__Hashr.index, S.Al__Buruj.index,
      S.Al__Mujadilah.index, S.Al__Layl.index, S.Al__Balad.index,
      S.Al__Muzzammil.index, S.Al__A_a_la.index, S.Al__Infitar.index,
      S.Al__Alaq.index, S.At__Taghabun.index, S.Al__Hujuraat.index,
      S.At__Taariq.index, S.Ash__Shams.index, S.As__Saff.index,
      S.Al__Mumtahanah.index, S.At__Talaq.index, S.At__Tahrim.index,
      S.Al__Jumu_a_ah.index, S.Al__Munafiqun.index, S.Ad__Dhuha.index,
      S.Al___a_Aadiyat.index, S.Al__Qaari_a_ah.index, S.Al__Humazah.index,
      S.Az__Zalzalah.index, S.Ash__Sharh.index, S.Al__Bayyinah.index,
      S.At__Tin.index, S.At__Takaathur.index, S.Al__Maa_a_un.index,
      S.Al__Fatihah.index, S.An__Naas.index, S.Al__Kaafirun.index,
      S.Al__Fil.index, S.Al__Masad.index, S.Al__Falaq.index,
      S.Al__Qadr.index, S.Quraish.index, S.Al__Ikhlas.index,
      S.Al___a_Asr.index, S.Al__Kawthar.index, S.An__Nasr.index, //
    ],
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: 'Order by Ruku Count',
    field: FILTER_FIELD.OrderByRukuCount,
    idxList: [
      S.Al__Baqarah.index, S.An__Nisa.index, S.Al__A_a_raf.index,
      S.Aali__a_Imran.index, S.Al__An_a_am.index, S.At__Tawbah.index,
      S.Al__Ma_a_idah.index, S.An__Nahl.index, S.Al__Kahf.index, S.Yusuf.index,
      S.Al__Isra.index, S.Yunus.index, S.Ash__Shu_a_ara.index, S.Hud.index,
      S.Al__Anfal.index, S.Al__Hajj.index, S.An__Nur.index, S.Al__Qasas.index,
      S.Al__Ahzaab.index, S.Ghafir.index, S.Ta__Ha.index, S.Az__Zumar.index,
      S.Az__Zukhruf.index, S.Ibrahim.index, S.Al__Anbiya.index,
      S.An__Naml.index, S.Al__Ankabut.index, S.Al__Hijr.index,
      S.Ar__Ra_a_d.index, S.Maryam.index, S.Fussilat.index, S.Al__Furqan.index,
      S.Ar__Rum.index, S.Saba.index, S.Al__Mu_a_minun.index, S.Saad.index,
      S.As__Saaffaat.index, S.Ash__Shura.index, S.Ya__Sin.index, S.Faatir.index,
      S.Al__Fath.index, S.Al__Ahqaaf.index, S.Muhammad.index,
      S.Al__Jaathiyah.index, S.Luqmaan.index, S.Al__Hadid.index,
      S.Al__Hashr.index, S.Al__Mujadilah.index, S.Al__Waqi_a_ah.index,
      S.Ad__Dukhaan.index, S.As__Sajdah.index, S.Ar__Rahman.index, S.Qaaf.index,
      S.Al__Mumtahanah.index, S.Al__Qamar.index, S.An__Najm.index,
      S.At__Tur.index, S.Adh__Dhaariyaat.index, S.Al__Hujuraat.index,
      S.Al__Muddaththir.index, S.Al__Jinn.index, S.Al__Haaqqa.index,
      S.Al__Qalam.index, S.At__Tahrim.index, S.At__Talaq.index,
      S.At__Taghabun.index, S.Ad__Dahr.index, S.An__Naazi_a_aat.index,
      S.An__Naba_a_.index, S.Al__Mursalaat.index, S.Al__Muzzammil.index,
      S.Nuh.index, S.Al__Ma_a_aarij.index, S.Al__Mulk.index,
      S.Al__Munafiqun.index, S.Al__Jumu_a_ah.index, S.As__Saff.index,
      S.Al__Inshiqaaq.index, S.Abasa.index, S.At__Takwir.index,
      S.Al__Fatihah.index, S.Al__Mutaffifin.index, S.Al__Qiyamah.index,
      S.Al__Buruj.index, S.Al__Ghaashiyah.index, S.Al__Fajr.index,
      S.Al__Bayyinah.index, S.Al__Infitar.index, S.At__Taariq.index,
      S.Al__A_a_la.index, S.Al__Balad.index, S.Al__Layl.index,
      S.Ad__Dhuha.index, S.Al__Alaq.index, S.Ash__Shams.index, S.At__Tin.index,
      S.Al__Qadr.index, S.An__Naas.index, S.Az__Zalzalah.index,
      S.Al___a_Aadiyat.index, S.Al__Qaari_a_ah.index, S.At__Takaathur.index,
      S.Al___a_Asr.index, S.Al__Humazah.index, S.Al__Fil.index, S.Quraish.index,
      S.Al__Maa_a_un.index, S.Al__Kawthar.index, S.Al__Kaafirun.index,
      S.An__Nasr.index, S.Al__Masad.index, S.Al__Ikhlas.index,
      S.Al__Falaq.index, S.Ash__Sharh.index, //
    ],
    tprMax: 38,
  ),
  const RelicSetFilter(
    tkLabel: 'Show Juz',
    field: FILTER_FIELD.ShowJuz,
    idxList: _relicOrder,
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: 'Revealed in Mecca',
    field: FILTER_FIELD.StartToEndDate,
    idxList: [
      S.Al__Fatihah.index, S.Al__An_a_am.index, S.Al__A_a_raf.index,
      S.Yunus.index, S.Hud.index, S.Yusuf.index, S.Ibrahim.index,
      S.Al__Hijr.index, S.An__Nahl.index, S.Al__Isra.index, S.Al__Kahf.index,
      S.Maryam.index, S.Ta__Ha.index, S.Al__Anbiya.index,
      S.Al__Mu_a_minun.index, S.Al__Furqan.index, S.Ash__Shu_a_ara.index,
      S.An__Naml.index, S.Al__Qasas.index, S.Al__Ankabut.index, S.Ar__Rum.index,
      S.Luqmaan.index, S.As__Sajdah.index, S.Saba.index, S.Faatir.index,
      S.Ya__Sin.index, S.As__Saaffaat.index, S.Saad.index, S.Az__Zumar.index,
      S.Ghafir.index, S.Fussilat.index, S.Ash__Shura.index, S.Az__Zukhruf.index,
      S.Ad__Dukhaan.index, S.Al__Jaathiyah.index, S.Al__Ahqaaf.index,
      S.Qaaf.index, S.Adh__Dhaariyaat.index, S.At__Tur.index, S.An__Najm.index,
      S.Al__Qamar.index, S.Al__Waqi_a_ah.index, S.Al__Mulk.index,
      S.Al__Qalam.index, S.Al__Haaqqa.index, S.Al__Ma_a_aarij.index,
      S.Nuh.index, S.Al__Jinn.index, S.Al__Muzzammil.index,
      S.Al__Muddaththir.index, S.Al__Qiyamah.index, S.Al__Mursalaat.index,
      S.An__Naba_a_.index, S.An__Naazi_a_aat.index, S.Abasa.index,
      S.At__Takwir.index, S.Al__Infitar.index, S.Al__Mutaffifin.index,
      S.Al__Inshiqaaq.index, S.Al__Buruj.index, S.At__Taariq.index,
      S.Al__A_a_la.index, S.Al__Ghaashiyah.index, S.Al__Fajr.index,
      S.Al__Balad.index, S.Ash__Shams.index, S.Al__Layl.index,
      S.Ad__Dhuha.index, S.Ash__Sharh.index, S.At__Tin.index, S.Al__Alaq.index,
      S.Al__Qadr.index, S.Al___a_Aadiyat.index, S.Al__Qaari_a_ah.index,
      S.At__Takaathur.index, S.Al___a_Asr.index, S.Al__Humazah.index,
      S.Al__Fil.index, S.Quraish.index, S.Al__Maa_a_un.index,
      S.Al__Kawthar.index, S.Al__Kaafirun.index, S.Al__Masad.index,
      S.Al__Ikhlas.index, S.Al__Falaq.index, S.An__Naas.index, //
    ],
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: 'Revealed in Medina',
    field: FILTER_FIELD.StartToEndDate,
    idxList: [
      S.Al__Baqarah.index, S.Aali__a_Imran.index, S.An__Nisa.index,
      S.Al__Ma_a_idah.index, S.Al__Anfal.index, S.At__Tawbah.index,
      S.Ar__Ra_a_d.index, S.Al__Hajj.index, S.An__Nur.index, S.Al__Ahzaab.index,
      S.Muhammad.index, S.Al__Fath.index, S.Al__Hujuraat.index,
      S.Ar__Rahman.index, S.Al__Hadid.index, S.Al__Mujadilah.index,
      S.Al__Hashr.index, S.Al__Mumtahanah.index, S.As__Saff.index,
      S.Al__Jumu_a_ah.index, S.Al__Munafiqun.index, S.At__Taghabun.index,
      S.At__Talaq.index, S.At__Tahrim.index, S.Ad__Dahr.index,
      S.Al__Bayyinah.index, S.Az__Zalzalah.index, S.An__Nasr.index, //
    ],
    tprMax: 38,
  ),
  RelicSetFilter(
    tkLabel: "Has Muqatta'at",
    field: FILTER_FIELD.HasMuqattaat,
    idxList: [
      S.Al__Baqarah.index, S.Aali__a_Imran.index, S.Al__A_a_raf.index,
      S.Yunus.index, S.Hud.index, S.Yusuf.index, S.Ar__Ra_a_d.index,
      S.Ibrahim.index, S.Al__Hijr.index, S.Maryam.index, S.Ta__Ha.index,
      S.Ash__Shu_a_ara.index, S.An__Naml.index, S.Al__Qasas.index,
      S.Al__Ankabut.index, S.Ar__Rum.index, S.Luqmaan.index,
      S.As__Sajdah.index, S.Ya__Sin.index, S.Saad.index, S.Ghafir.index,
      S.Fussilat.index, S.Ash__Shura.index, S.Az__Zukhruf.index,
      S.Ad__Dukhaan.index, S.Al__Jaathiyah.index, S.Al__Ahqaaf.index,
      S.Qaaf.index, S.Al__Qalam.index, //
    ],
    tprMax: 38,
  ),
];

/// S = Surah
enum S {
  Al__Fatihah,
  Al__Baqarah,
  Aali__a_Imran,
  An__Nisa,
  Al__Ma_a_idah,
  Al__An_a_am,
  Al__A_a_raf,
  Al__Anfal,
  At__Tawbah,
  Yunus,
  Hud,
  Yusuf,
  Ar__Ra_a_d,
  Ibrahim,
  Al__Hijr,
  An__Nahl,
  Al__Isra,
  Al__Kahf,
  Maryam,
  Ta__Ha,
  Al__Anbiya,
  Al__Hajj,
  Al__Mu_a_minun,
  An__Nur,
  Al__Furqan,
  Ash__Shu_a_ara,
  An__Naml,
  Al__Qasas,
  Al__Ankabut,
  Ar__Rum,
  Luqmaan,
  As__Sajdah,
  Al__Ahzaab,
  Saba,
  Faatir,
  Ya__Sin,
  As__Saaffaat,
  Saad,
  Az__Zumar,
  Ghafir,
  Fussilat,
  Ash__Shura,
  Az__Zukhruf,
  Ad__Dukhaan,
  Al__Jaathiyah,
  Al__Ahqaaf,
  Muhammad,
  Al__Fath,
  Al__Hujuraat,
  Qaaf,
  Adh__Dhaariyaat,
  At__Tur,
  An__Najm,
  Al__Qamar,
  Ar__Rahman,
  Al__Waqi_a_ah,
  Al__Hadid,
  Al__Mujadilah,
  Al__Hashr,
  Al__Mumtahanah,
  As__Saff,
  Al__Jumu_a_ah,
  Al__Munafiqun,
  At__Taghabun,
  At__Talaq,
  At__Tahrim,
  Al__Mulk,
  Al__Qalam,
  Al__Haaqqa,
  Al__Ma_a_aarij,
  Nuh,
  Al__Jinn,
  Al__Muzzammil,
  Al__Muddaththir,
  Al__Qiyamah,
  Ad__Dahr,
  Al__Mursalaat,
  An__Naba_a_,
  An__Naazi_a_aat,
  Abasa,
  At__Takwir,
  Al__Infitar,
  Al__Mutaffifin,
  Al__Inshiqaaq,
  Al__Buruj,
  At__Taariq,
  Al__A_a_la,
  Al__Ghaashiyah,
  Al__Fajr,
  Al__Balad,
  Ash__Shams,
  Al__Layl,
  Ad__Dhuha,
  Ash__Sharh,
  At__Tin,
  Al__Alaq,
  Al__Qadr,
  Al__Bayyinah,
  Az__Zalzalah,
  Al___a_Aadiyat,
  Al__Qaari_a_ah,
  At__Takaathur,
  Al___a_Asr,
  Al__Humazah,
  Al__Fil,
  Quraish,
  Al__Maa_a_un,
  Al__Kawthar,
  Al__Kaafirun,
  An__Nasr,
  Al__Masad,
  Al__Ikhlas,
  Al__Falaq,
  An__Naas,
}

enum REVELATION_PLACE {
  Makkah,
  Madinah,
}
