import 'package:hapi/main_controller.dart';
import 'package:hapi/quran/quran.dart';
import 'package:hapi/relic/relic.dart';

class Prophet extends Relic {
  Prophet({
    required Map<int, int> ajrLevels,
    required RELIC_ID relicId,
    required String trKeyEndTag,
    required String? dateEra,
    required int? dateBegin,
    required int? dateEnd,
    required this.mentionsInQuran,
    required this.sentTo,
    required this.nabi,
    this.rasul,
    this.ulualazm,
    this.nameLatin,
    this.trKeyNameNicknamesAr,
    this.locationBirth,
    this.locationDeath,
    this.tomb,
    this.predecessorAr,
    this.successorAr,
    this.motherAr,
    this.fatherAr,
    this.spousesAr,
    this.childrenAr,
    this.relativesAr,
    this.kitabAr,
    this.livedDuring,
  }) : super(
          ajrLevel: ajrLevels[relicId.index],
          relicId: relicId,
          relicType: RELIC_TYPE.Prophet,
          nameEn: trKeyEndTag,
          nameAr: a('a.$trKeyEndTag'),
          trKeySummary: 'ps.$trKeyEndTag',
          trKeySummary2: 'pq.$trKeyEndTag',
          dateEra: dateEra,
          dateBegin: dateBegin,
          dateEnd: dateEnd,
        );
  // Prophet (nabī) نَبِيّ	Messenger (rasūl) رَسُول
  // Archprophet (ʾulu al-'azm)
  final int mentionsInQuran;
  // nation the prophet was sent to:
  final String sentTo;
  // final List<QV> quranVerses;
  final QV nabi;

  final QV? rasul;
  final List<QV>? ulualazm;
  final String? nameLatin;
  final List<String>? trKeyNameNicknamesAr;
  final String? locationBirth;
  final String? locationDeath;
  final String? tomb;
  final String? predecessorAr;
  final String? successorAr;
  final String? motherAr;
  final String? fatherAr;
  final List<String>? spousesAr;
  final List<String>? childrenAr;
  final List<String>? relativesAr;
  final String? kitabAr;
  final String? livedDuring;
}

List<Prophet> prophets = [];
initProphets(Map<int, int> ajrLevels) {
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Adam,
      trKeyEndTag: 'Adam',
      dateEra: 'p.Birth of humanity',
      dateBegin: -3400000,
      dateEnd: -3399050,
      mentionsInQuran: 25,
      sentTo: 'p.Earth (4:1)',
      nabi: QV(2, 31),
      rasul: QV(2, 31),
      nameLatin: 'Adam',
      locationBirth: 'a.Jennah',
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: ['a.Hawwa'],
      childrenAr: ['a.Habel', 'a.Qabel', 'a.Sheth'],
      relativesAr: null,
      kitabAr: null,
      livedDuring: 'Birth of humanity'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Idris,
      trKeyEndTag: 'Idris',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 2,
      sentTo: 'p.Babylon',
      nabi: QV(19, 56),
      nameLatin: 'Enoch',
      locationBirth: 'p.Babylon',
      locationDeath: 'p.Hebron, Shaam',
      tomb: 'Ibrahimi Mosque, Hebron',
      predecessorAr: 'p.Sheth',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: ["a.'Anaq"],
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Nuh,
      trKeyEndTag: 'Nuh',
      dateEra: 'p.Great Flood',
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 43,
      sentTo: 'p.The people of Noah (26:105)',
      nabi: QV(6, 89),
      rasul: QV(25, 107),
      ulualazm: [QV(46, 35), QV(33, 7)],
      nameLatin: 'Noah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'a.Idris',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: 'Great Flood'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Hud,
      trKeyEndTag: 'Hud',
      dateEra: null,
      dateBegin: -2400,
      dateEnd: null,
      mentionsInQuran: 7,
      sentTo: 'p.Ad tribe (7:65)',
      nabi: QV(26, 125),
      rasul: QV(26, 125),
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'a.Nuh',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: ['a.Shem', 'a.Ham', 'a.Yam', 'a.Japheth'],
      relativesAr: null,
      kitabAr: null,
      livedDuring: 'c. 2400 BC[78]'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Saleh,
      trKeyEndTag: 'Saleh',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 9,
      sentTo: 'p.Thamud tribe (7:73)',
      nabi: QV(26, 143),
      rasul: QV(26, 143),
      nameLatin: 'Selah',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Hasik (present day Oman)',
      predecessorAr: 'a.Hud',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['a.Thamud'],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Ibrahim,
      trKeyEndTag: 'Ibrahim',
      dateEra: 'p.Migration of the Jews to Iraq',
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 69,
      sentTo: 'p.Babylon, The people of Iraq & Syria (22:43)',
      nabi: QV(19, 41),
      rasul: QV(9, 70),
      ulualazm: [QV(2, 124)],
      nameLatin: 'Abraham',
      trKeyNameNicknamesAr: ['a.Khalīlullāh'],
      locationBirth: 'p.Ur al-Chaldees, Bilād ar-Rāfidayn',
      locationDeath: 'p.Hebron, Shaam',
      tomb: 'Ibrahimi Mosque, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Mahalath',
      fatherAr: 'a.Aazar',
      spousesAr: null,
      childrenAr: null,
      relativesAr: [
        at('at.{0} (nephew)', ['a.Lut'])
      ],
      kitabAr: 'Scrolls of Abraham (87:19)',
      livedDuring: 'Migration of the Jews to Iraq'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Lut,
      trKeyEndTag: 'Lut',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 27,
      sentTo: 'p.Sodom and Gomorrah (7:80)',
      nabi: QV(6, 86),
      rasul: QV(37, 133),
      nameLatin: 'Lot',
      locationBirth: null,
      locationDeath: "p.Bani Na'im",
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: 'p.Haran',
      spousesAr: null,
      childrenAr: ["a.Isma'il", "a.Is'ḥaq"],
      relativesAr: ['Ibrahim (uncle)'],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Isma_il,
      trKeyEndTag: "Isma'il",
      dateEra: null,
      dateBegin: -1800,
      dateEnd: -1664,
      mentionsInQuran: 12,
      sentTo: 'p.Pre-Islamic Arabia (Mecca)',
      nabi: QV(19, 54),
      rasul: QV(19, 54),
      nameLatin: 'Ishmael',
      locationBirth: 'p.Palestine/Canaan',
      locationDeath: 'p.Age 136, Mecca, Arabia',
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Hajar',
      fatherAr: 'a.Ibrahim',
      spousesAr: null,
      childrenAr: null,
      relativesAr: [
        at("{0} (half-brother)", ["p.Is'haq"])
      ],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Is_haq,
      trKeyEndTag: "Is'haq",
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 17,
      sentTo: 'p.Palestine/Canaan',
      nabi: QV(19, 49),
      nameLatin: 'Isaac',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Cave of the Patriarchs, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Sarah',
      fatherAr: 'a.Ibrahim',
      spousesAr: null,
      childrenAr: ['Children of Isma‘il (Arabs)'],
      relativesAr: [
        at('{0} (half-brother)', ["a.Isma'il"]),
        'forefather of the Twelve Tribes of Israel'
      ],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Yaqub,
      trKeyEndTag: 'Yaqub',
      dateEra: 'p.Twelve Tribes of Israel',
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 16,
      sentTo: 'p.Palestine/Canaan',
      nabi: QV(19, 49),
      nameLatin: 'Jacob',
      trKeyNameNicknamesAr: ['a.Israel'],
      locationBirth: null,
      locationDeath: null,
      tomb: 'Cave of the Patriarchs, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Rafeqa',
      fatherAr: "a.Is'haq",
      spousesAr: null,
      childrenAr: ['a.Yaqub', 'a.Esau'],
      relativesAr: null,
      kitabAr: null,
      livedDuring: 'Twelve Tribes of Israel'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Yusuf,
      trKeyEndTag: 'Yusuf',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 27,
      sentTo: 'p.Ancient Kingdom of Egypt',
      nabi: QV(4, 89),
      rasul: QV(40, 34),
      nameLatin: 'Joseph',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Rahil',
      fatherAr: 'a.Yaqub',
      spousesAr: null,
      childrenAr: ['a.Yusuf', 'a.Bunyamin', '10 others'],
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Ayyub,
      trKeyEndTag: 'Ayyub',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 4,
      sentTo: 'p.Edom',
      nabi: QV(4, 89),
      nameLatin: 'Job',
      locationBirth: null,
      locationDeath: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Shu_ayb,
      trKeyEndTag: "Shu'ayb",
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 9,
      sentTo: 'p.Midian (7:85)',
      nabi: QV(26, 178),
      rasul: QV(26, 178),
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Musa,
      trKeyEndTag: 'Musa',
      dateEra: 'p.Ancient Pharaoh Kingdoms Of Egypt',
      dateBegin: -1300,
      dateEnd: -1200,
      mentionsInQuran: 136,
      sentTo: 'p.Egypt Pharaoh and his establishment (43:46)',
      nabi: QV(20, 47),
      rasul: QV(20, 47),
      ulualazm: [QV(46, 35), QV(33, 7)],
      nameLatin: 'Moses',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Harun (Brother)'],
      kitabAr: 'Ten Commandments, Tawrah (Torah); Scrolls of Moses (53:36)',
      livedDuring:
          'c. 1400s BCE – c. 1300s BCE, or c. 1300s BCE – c. 1200s BCE'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Harun,
      trKeyEndTag: 'Harun',
      dateEra: null,
      dateBegin: -1300,
      dateEnd: -1200,
      mentionsInQuran: 20,
      sentTo: 'p.Egypt Pharaoh and his establishment (43:46)',
      nabi: QV(19, 53),
      rasul: QV(20, 47),
      nameLatin: 'Aaron',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'p.Musa',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Musa (Brother)'],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Dawud,
      trKeyEndTag: 'Dawud',
      dateEra: 'p.King of Israel',
      dateBegin: -1000,
      dateEnd: -971,
      mentionsInQuran: 16,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      rasul: QV(6, 89),
      nameLatin: 'David',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Tomb of Aaron',
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: 'Zabur (Psalms) (17:55, 4:163, 17:55, 21:105)',
      livedDuring: 'c. 1000s BCE – c. 971 BCE'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Suleyman,
      trKeyEndTag: 'Suleyman',
      dateEra: 'p.King of Israel',
      dateBegin: -971,
      dateEnd: -931,
      mentionsInQuran: 17,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      nameLatin: 'Solomon',
      locationBirth: 'p.Jerusalem, Kingdom of Israel',
      locationDeath: 'p.Jerusalem, Kingdom of Israel',
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: 'a.Dawud',
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: 'c. 971 BCE – c. 931 BCE'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Ilyas,
      trKeyEndTag: 'Ilyas',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 2,
      sentTo: 'p.Sumaria, The people of Ilyas (37:124)',
      nabi: QV(6, 89),
      rasul: QV(37, 123),
      nameLatin: 'Elijah',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'A 14th-century shrine built on top of the supposed grave of Aaron on Jabal Hārūn near Petra, Jordan',
      predecessorAr: 'p.Suleyman',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Alyasa,
      trKeyEndTag: 'Alyasa',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 2,
      sentTo: 'p.Samaria, Eastern Arabia, & Persia',
      nabi: QV(6, 89),
      nameLatin: 'Elisha',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'According to one Islamic tradition, the tomb of Aaron is located on Jabal Harun (Arabic: جَـبـل هَـارون, Mountain of Aaron), near Petra in Jordan, with another tradition placing it in Sinai.',
      predecessorAr: 'a.Ilyas',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Yunus,
      trKeyEndTag: 'Yunus',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 4,
      sentTo: 'p.Ninevah, The people of Yunus (10:98)',
      nabi: QV(6, 89),
      rasul: QV(37, 139),
      nameLatin: 'Jonah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'p.Alyasa',
      successorAr: null,
      motherAr: null,
      fatherAr: 'p.Amittai',
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Dhu_al_Kifl,
      trKeyEndTag: 'Dhu al-Kifl',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 2,
      sentTo: 'p.Babylon',
      nabi: QV(21, 85, ayaEnd: 86),
      nameLatin: 'Ezekiel?, Buddha?, Joshua?, Obadiah?, Isaiah?',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'At 1,350.0 m (4,429.1 feet) above sea-level, Jabal Hārūn is the highest peak in the area and a place of great sanctity to the local people. A 14th-century Mamluk mosque stands there with its white dome visible from most areas in and around Petra."',
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Zakariyya,
      trKeyEndTag: 'Zakariyya',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 7,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      nameLatin: 'Zechariah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Yahya,
      trKeyEndTag: 'Yahya',
      dateEra: null,
      dateBegin: null,
      dateEnd: null,
      mentionsInQuran: 5,
      sentTo: 'p.Jerusalem',
      nabi: QV(3, 39),
      nameLatin: 'John',
      locationBirth: null,
      locationDeath: null,
      predecessorAr: 'p.Zakariya',
      successorAr: null,
      motherAr: 'a.Elizabeth', // TODO
      fatherAr: 'a.Zakariya',
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Isa (cousin)'],
      kitabAr: null,
      livedDuring: null));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Isa,
      trKeyEndTag: 'Isa',
      dateEra: null,
      dateBegin: -4,
      dateEnd: 30,
      mentionsInQuran: 25,
      sentTo: 'p.Banu Israel, The Children of Israel (61:6)',
      nabi: QV(19, 30),
      rasul: QV(4, 171),
      ulualazm: [QV(42, 13)],
      nameLatin: 'Jesus',
      trKeyNameNicknamesAr: ['a.Masih'],
      locationBirth: 'p.Judea, Roman Empire',
      locationDeath:
          'p.Age 33, Raised to Heaven in 30 CE, Gethsemane, Jerusalem, Roman Empire',
      tomb: 'Al-Ḥaram ash-Sharīf, Jerusalem',
      predecessorAr: 'p.Yahya',
      successorAr: null,
      motherAr: 'a.Maryam',
      fatherAr: 'None',
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Zakariyya (uncle)', 'Yahya (cousin)'],
      kitabAr: 'Injil (Gospel) (57:27)',
      livedDuring: 'c. 4 BCE – c. 30 CE'));
  prophets.add(Prophet(
      ajrLevels: ajrLevels,
      relicId: RELIC_ID.Prophet_Muhammad,
      trKeyEndTag: 'Muhammad',
      dateEra: null,
      dateBegin: 570,
      dateEnd: 632,
      mentionsInQuran: 4,
      sentTo: 'p.All humanity and jinn (21:107)',
      nabi: QV(33, 40),
      rasul: QV(33, 40),
      ulualazm: [QV(2, 124)],
      trKeyNameNicknamesAr: [
        'a.Khātam al-Nabiyyīn',
        'a.Ahmad',
        'a.Al-Mahi',
        'a.al-Hashir',
        'a.Al-Aqib',
        'a.al-Nabī',
        'a.Rasūl’Allāh',
        'a.al-Ḥabīb',
        'a.Ḥabīb Allāh',
        "a.al-Raḥmah lil-'Ālamīn",
        'a.An-Nabiyyu l-Ummiyy',
        'a.Mustafa'
      ],
      locationBirth: at(
          "at.{0}, 12 Rabi' al-Awwal 53 BH (570 CE), Mecca, Hejaz, Arabia",
          ['a.Aliathnayn']),
      locationDeath: at(
          "at.{0} 12 Rabi' al-Awwal 11 AH (8 June 632 CE), Medina, Hejaz, Arabia",
          ['a.Aliathnayn']),
      tomb: null,
      predecessorAr: 'a.Isa',
      successorAr: null,
      motherAr: 'a.Amina bint Wahb',
      fatherAr: 'a.Abdullah ibn Abd al-Muttalib',
      spousesAr: null,
      childrenAr: [
        'Al-Qasim (598–601)',
        'Zainab (599–629)',
        'Ruqayyah (601–624)',
        'Umm Kulthum (603–630)',
        'Fatimah (605–632)',
        'Abdullah (611–613)',
        'Ibrahim (630–632)'
      ],
      relativesAr: null,
      kitabAr: 'Quran (42:7)',
      livedDuring: '571 – 632'));
}
