import 'package:hapi/main_controller.dart';
import 'package:hapi/quran/quran.dart';
import 'package:hapi/relic/relic.dart';
import 'package:hapi/tarikh/tarikh_controller.dart';
import 'package:hapi/tarikh/timeline/timeline_entry.dart';

class Prophet extends Relic {
  Prophet({
    // TimelineEntry data:
    required String trKeyEndTagLabel,
    required era,
    required double startMs,
    required double endMs,
    required TimelineAsset asset,
    // Relic data:
    required RELIC_ID relicId,
    required int ajrLevel,
    // Required prophet data:
    required this.sentTo,
    required this.quranMentionCount,
    required this.nabi,
    // Optional prophet data:
    this.rasul,
    this.uluAlAzm,
    this.nameLatin,
    this.trKeyNameNicknamesAr,
    this.locationBirth,
    this.locationDeath,
    this.tomb,
    this.predecessorAr,
    this.successorAr,
    this.motherAr,
    this.fatherAr,
    this.spousesAr,
    this.childrenAr,
    this.relativesAr,
    this.kitabAr,
  }) : super(
          // TimelineEntry data:
          trKeyEndTagLabel: trKeyEndTagLabel,
          era: era,
          startMs: startMs,
          endMs: endMs,
          asset: asset,
          // Relic data:
          relicType: RELIC_TYPE.Prophet,
          relicId: relicId,
          ajrLevel: ajrLevel,
          trKeySummary: 'ps.$trKeyEndTagLabel', // ps=Prophet Summary
          trKeySummary2: 'pq.$trKeyEndTagLabel', // pq=Prophet Quran mentions
        );
  // Required prophet data:
  final int quranMentionCount;
  final String sentTo; // nation the prophet was sent to:
  final QV nabi; // Prophet (nabī) نَبِيّ
  // Optional prophet data:
  final QV? rasul; //Messenger (rasūl) رَسُول
  final List<QV>? uluAlAzm; // Archprophet (ʾUlu Al-'Azm)
  final String? nameLatin;
  final List<String>? trKeyNameNicknamesAr;
  final String? locationBirth;
  final String? locationDeath;
  final String? tomb;
  final String? predecessorAr;
  final String? successorAr;
  final String? motherAr;
  final String? fatherAr;
  final List<String>? spousesAr;
  final List<String>? childrenAr;
  final List<String>? relativesAr;
  final String? kitabAr;

  bool isRasul() => rasul != null;
  bool isUluAlAzm() => uluAlAzm != null && uluAlAzm!.isNotEmpty;
}

List<Prophet> prophets = [];
initProphets(Map<int, int> ajrLevels) async {
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Adam.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Adam.index]!,
      relicId: RELIC_ID.Prophet_Adam,
      trKeyEndTagLabel: 'Adam',
      era: 'p.Birth of humanity',
      startMs: -3400000,
      endMs: -3399050,
      quranMentionCount: 25,
      sentTo: 'p.First man on Earth (4:1)',
      nabi: QV(2, 31),
      rasul: QV(2, 31),
      nameLatin: 'Adam',
      locationBirth: 'a.Jennah',
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: 'p.Created by Allah without a mother',
      fatherAr: 'p.Created by Allah without a father',
      spousesAr: ['a.Hawwa'],
      childrenAr: ['a.Habel', 'a.Qabel', 'a.Sheth'],
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Idris.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Idris.index]!,
      relicId: RELIC_ID.Prophet_Idris,
      trKeyEndTagLabel: 'Idris',
      era: 'p.Early humans',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 2,
      sentTo: 'p.Babylon',
      nabi: QV(19, 56),
      nameLatin: 'Enoch',
      locationBirth: 'p.Babylon',
      locationDeath: 'p.Hebron, Shaam',
      tomb: 'Ibrahimi Mosque, Hebron',
      predecessorAr: 'p.Sheth',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: ["a.'Anaq"],
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Nuh.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Nuh.index]!,
      relicId: RELIC_ID.Prophet_Nuh,
      trKeyEndTagLabel: 'Nuh',
      era: 'p.Great Flood',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 43,
      sentTo: 'p.The people of Noah (26:105)',
      nabi: QV(6, 89),
      rasul: QV(25, 107),
      uluAlAzm: [QV(46, 35), QV(33, 7)],
      nameLatin: 'Noah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'a.Idris',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Hud.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Hud.index]!,
      relicId: RELIC_ID.Prophet_Hud,
      trKeyEndTagLabel: 'Hud',
      era: 'Unknown',
      startMs: -2400,
      endMs: 0,
      quranMentionCount: 7,
      sentTo: 'p.Ad tribe (7:65)',
      nabi: QV(26, 125),
      rasul: QV(26, 125),
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'a.Nuh',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: ['a.Shem', 'a.Ham', 'a.Yam', 'a.Japheth'],
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Saleh.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Saleh.index]!,
      relicId: RELIC_ID.Prophet_Saleh,
      trKeyEndTagLabel: 'Saleh',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 9,
      sentTo: 'p.Thamud tribe (7:73)',
      nabi: QV(26, 143),
      rasul: QV(26, 143),
      nameLatin: 'Selah',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Hasik (present day Oman)',
      predecessorAr: 'a.Hud',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['a.Thamud'],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Ibrahim.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Ibrahim.index]!,
      relicId: RELIC_ID.Prophet_Ibrahim,
      trKeyEndTagLabel: 'Ibrahim',
      era: 'p.Migration of the Jews to Iraq',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 69,
      sentTo: 'p.Babylon, The people of Iraq & Syria (22:43)',
      nabi: QV(19, 41),
      rasul: QV(9, 70),
      uluAlAzm: [QV(2, 124)],
      nameLatin: 'Abraham',
      trKeyNameNicknamesAr: ['a.Khalīlullāh'],
      locationBirth: 'p.Ur al-Chaldees, Bilād ar-Rāfidayn',
      locationDeath: 'p.Hebron, Shaam',
      tomb: 'Ibrahimi Mosque, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Mahalath',
      fatherAr: 'a.Aazar',
      spousesAr: null,
      childrenAr: null,
      relativesAr: [
        at('at.{0} (nephew)', ['a.Lut'])
      ],
      kitabAr: 'Scrolls of Abraham (87:19)'));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Lut.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Lut.index]!,
      relicId: RELIC_ID.Prophet_Lut,
      trKeyEndTagLabel: 'Lut',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 27,
      sentTo: 'p.Sodom and Gomorrah (7:80)',
      nabi: QV(6, 86),
      rasul: QV(37, 133),
      nameLatin: 'Lot',
      locationBirth: null,
      locationDeath: "p.Bani Na'im",
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: 'p.Haran',
      spousesAr: null,
      childrenAr: ["a.Isma'il", "a.Is'ḥaq"],
      relativesAr: ['Ibrahim (uncle)'],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Isma_il.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Isma_il.index]!,
      relicId: RELIC_ID.Prophet_Isma_il,
      trKeyEndTagLabel: "Isma'il",
      era: 'Unknown',
      startMs: -1800,
      endMs: -1664,
      quranMentionCount: 12,
      sentTo: 'p.Pre-Islamic Arabia (Mecca)',
      nabi: QV(19, 54),
      rasul: QV(19, 54),
      nameLatin: 'Ishmael',
      locationBirth: 'p.Palestine/Canaan',
      locationDeath: 'p.Age 136, Mecca, Arabia',
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Hajar',
      fatherAr: 'a.Ibrahim',
      spousesAr: null,
      childrenAr: null,
      relativesAr: [
        at('at.{0} (Half-Brother)', ["p.Is'haq"])
      ],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Is_haq.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Is_haq.index]!,
      relicId: RELIC_ID.Prophet_Is_haq,
      trKeyEndTagLabel: "Is'haq",
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 17,
      sentTo: 'p.Palestine/Canaan',
      nabi: QV(19, 49),
      nameLatin: 'Isaac',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Cave of the Patriarchs, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Sarah',
      fatherAr: 'a.Ibrahim',
      spousesAr: null,
      childrenAr: ['Children of Isma‘il (Arabs)'],
      relativesAr: [
        at('{0} (half-brother)', ["a.Isma'il"]),
        'forefather of the Twelve Tribes of Israel'
      ],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Yaqub.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Yaqub.index]!,
      relicId: RELIC_ID.Prophet_Yaqub,
      trKeyEndTagLabel: 'Yaqub',
      era: 'p.Twelve Tribes of Israel',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 16,
      sentTo: 'p.Palestine/Canaan',
      nabi: QV(19, 49),
      nameLatin: 'Jacob',
      trKeyNameNicknamesAr: ['a.Israel'],
      locationBirth: null,
      locationDeath: null,
      tomb: 'Cave of the Patriarchs, Hebron',
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Rafeqa',
      fatherAr: "a.Is'haq",
      spousesAr: null,
      childrenAr: ['a.Yaqub', 'a.Esau'],
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Yusuf.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Yusuf.index]!,
      relicId: RELIC_ID.Prophet_Yusuf,
      trKeyEndTagLabel: 'Yusuf',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 27,
      sentTo: 'p.Ancient Kingdom of Egypt',
      nabi: QV(4, 89),
      rasul: QV(40, 34),
      nameLatin: 'Joseph',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: 'a.Rahil',
      fatherAr: 'a.Yaqub',
      spousesAr: null,
      childrenAr: ['a.Yusuf', 'a.Bunyamin', '10 others'],
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Ayyub.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Ayyub.index]!,
      relicId: RELIC_ID.Prophet_Ayyub,
      trKeyEndTagLabel: 'Ayyub',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 4,
      sentTo: 'p.Edom',
      nabi: QV(4, 89),
      nameLatin: 'Job',
      locationBirth: null,
      locationDeath: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Shu_ayb.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Shu_ayb.index]!,
      relicId: RELIC_ID.Prophet_Shu_ayb,
      trKeyEndTagLabel: "Shu'ayb",
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 9,
      sentTo: 'p.Midian (7:85)',
      nabi: QV(26, 178),
      rasul: QV(26, 178),
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Musa.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Musa.index]!,
      relicId: RELIC_ID.Prophet_Musa,
      trKeyEndTagLabel: 'Musa',
      era: 'p.Ancient Pharaoh Kingdoms Of Egypt',
      startMs: -1300,
      endMs: -1200,
      quranMentionCount: 136,
      sentTo: 'p.Egypt Pharaoh and his establishment (43:46)',
      nabi: QV(20, 47),
      rasul: QV(20, 47),
      uluAlAzm: [QV(46, 35), QV(33, 7)],
      nameLatin: 'Moses',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Harun (Brother)'],
      kitabAr: 'p.Ten Commandments, Tawrah (Torah); Scrolls of Moses (53:36)'));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Harun.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Harun.index]!,
      relicId: RELIC_ID.Prophet_Harun,
      trKeyEndTagLabel: 'Harun',
      era: 'Unknown',
      startMs: -1300,
      endMs: -1200,
      quranMentionCount: 20,
      sentTo: 'p.Egypt Pharaoh and his establishment (43:46)',
      nabi: QV(19, 53),
      rasul: QV(20, 47),
      nameLatin: 'Aaron',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'p.Musa',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Musa (Brother)'],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Dawud.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Dawud.index]!,
      relicId: RELIC_ID.Prophet_Dawud,
      trKeyEndTagLabel: 'Dawud',
      era: 'p.King of Israel',
      startMs: -1000,
      endMs: -971,
      quranMentionCount: 16,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      rasul: QV(6, 89),
      nameLatin: 'David',
      locationBirth: null,
      locationDeath: null,
      tomb: 'Tomb of Aaron',
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: 'Zabur (Psalms) (17:55, 4:163, 17:55, 21:105)'));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Suleyman.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Suleyman.index]!,
      relicId: RELIC_ID.Prophet_Suleyman,
      trKeyEndTagLabel: 'Suleyman',
      era: 'p.King of Israel',
      startMs: -971,
      endMs: -931,
      quranMentionCount: 17,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      nameLatin: 'Solomon',
      locationBirth: 'p.Jerusalem, Kingdom of Israel',
      locationDeath: 'p.Jerusalem, Kingdom of Israel',
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: 'a.Dawud',
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Ilyas.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Ilyas.index]!,
      relicId: RELIC_ID.Prophet_Ilyas,
      trKeyEndTagLabel: 'Ilyas',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 2,
      sentTo: 'p.Sumaria, The people of Ilyas (37:124)',
      nabi: QV(6, 89),
      rasul: QV(37, 123),
      nameLatin: 'Elijah',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'A 14th-century shrine built on top of the supposed grave of Aaron on Jabal Hārūn near Petra, Jordan',
      predecessorAr: 'p.Suleyman',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Alyasa.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Alyasa.index]!,
      relicId: RELIC_ID.Prophet_Alyasa,
      trKeyEndTagLabel: 'Alyasa',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 2,
      sentTo: 'p.Samaria, Eastern Arabia, & Persia',
      nabi: QV(6, 89),
      nameLatin: 'Elisha',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'According to one Islamic tradition, the tomb of Aaron is located on Jabal Harun (Arabic: جَـبـل هَـارون, Mountain of Aaron), near Petra in Jordan, with another tradition placing it in Sinai.',
      predecessorAr: 'a.Ilyas',
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Yunus.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Yunus.index]!,
      relicId: RELIC_ID.Prophet_Yunus,
      trKeyEndTagLabel: 'Yunus',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 4,
      sentTo: 'p.Ninevah, The people of Yunus (10:98)',
      nabi: QV(6, 89),
      rasul: QV(37, 139),
      nameLatin: 'Jonah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: 'p.Alyasa',
      successorAr: null,
      motherAr: null,
      fatherAr: 'p.Amittai',
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Dhu_al_Kifl.name.split('_')[1]}.png',
          528,
          528,
          -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Dhu_al_Kifl.index]!,
      relicId: RELIC_ID.Prophet_Dhu_al_Kifl,
      trKeyEndTagLabel: 'Dhu al-Kifl',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 2,
      sentTo: 'p.Babylon',
      nabi: QV(21, 85, ayaEnd: 86),
      nameLatin: 'Ezekiel?, Buddha?, Joshua?, Obadiah?, Isaiah?',
      locationBirth: null,
      locationDeath: null,
      tomb:
          'At 1,350.0 m (4,429.1 feet) above sea-level, Jabal Hārūn is the highest peak in the area and a place of great sanctity to the local people. A 14th-century Mamluk mosque stands there with its white dome visible from most areas in and around Petra."',
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Zakariyya.name.split('_')[1]}.png',
          528,
          528,
          -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Zakariyya.index]!,
      relicId: RELIC_ID.Prophet_Zakariyya,
      trKeyEndTagLabel: 'Zakariyya',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 7,
      sentTo: 'p.Jerusalem',
      nabi: QV(6, 89),
      nameLatin: 'Zechariah',
      locationBirth: null,
      locationDeath: null,
      tomb: null,
      predecessorAr: null,
      successorAr: null,
      motherAr: null,
      fatherAr: null,
      spousesAr: null,
      childrenAr: null,
      relativesAr: null,
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Yahya.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Yahya.index]!,
      relicId: RELIC_ID.Prophet_Yahya,
      trKeyEndTagLabel: 'Yahya',
      era: 'Unknown',
      startMs: 0,
      endMs: 0,
      quranMentionCount: 5,
      sentTo: 'p.Jerusalem',
      nabi: QV(3, 39),
      nameLatin: 'John',
      locationBirth: null,
      locationDeath: null,
      predecessorAr: 'p.Zakariya',
      successorAr: null,
      motherAr: 'a.Elizabeth', // TODO
      fatherAr: 'a.Zakariya',
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Isa (cousin)'],
      kitabAr: null));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Isa.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Isa.index]!,
      relicId: RELIC_ID.Prophet_Isa,
      trKeyEndTagLabel: 'Isa',
      era: 'Unknown',
      startMs: -4,
      endMs: 30,
      quranMentionCount: 25,
      sentTo: 'p.Banu Israel, The Children of Israel (61:6)',
      nabi: QV(19, 30),
      rasul: QV(4, 171),
      uluAlAzm: [QV(42, 13)],
      nameLatin: 'Jesus',
      trKeyNameNicknamesAr: ['a.Masih'],
      locationBirth: 'p.Judea, Roman Empire',
      locationDeath:
          'p.Age 33, Raised to Heaven in 30 CE, Gethsemane, Jerusalem, Roman Empire',
      tomb: 'Al-Ḥaram ash-Sharīf, Jerusalem',
      predecessorAr: 'p.Yahya',
      successorAr: null,
      motherAr: 'a.Maryam',
      fatherAr: 'p.Created by Allah without a father',
      spousesAr: null,
      childrenAr: null,
      relativesAr: ['Zakariyya (uncle)', 'Yahya (cousin)'],
      kitabAr: 'Injil (Gospel) (57:27)'));
  prophets.add(Prophet(
      asset: await TarikhController.tih.loadImageAsset(
          '${RELIC_ID.Prophet_Muhammad.name.split('_')[1]}.png', 528, 528, -40),
      ajrLevel: ajrLevels[RELIC_ID.Prophet_Muhammad.index]!,
      relicId: RELIC_ID.Prophet_Muhammad,
      trKeyEndTagLabel: 'Muhammad',
      era: 'Rebirth of Islam',
      startMs: 570, // TODO 571?
      endMs: 632,
      quranMentionCount: 4,
      sentTo: 'p.All humanity and jinn (21:107)',
      nabi: QV(33, 40),
      rasul: QV(33, 40),
      uluAlAzm: [QV(2, 124)],
      trKeyNameNicknamesAr: [
        'a.Khātam al-Nabiyyīn',
        'a.Ahmad',
        'a.Al-Mahi',
        'a.al-Hashir',
        'a.Al-Aqib',
        'a.al-Nabī',
        'a.Rasūl’Allāh',
        'a.al-Ḥabīb',
        'a.Ḥabīb Allāh',
        "a.al-Raḥmah lil-'Ālamīn",
        'a.An-Nabiyyu l-Ummiyy',
        'a.Mustafa'
      ],
      locationBirth: at(
          "at.{0}, 12 Rabi' al-Awwal 53 BH (570 CE), Mecca, Hejaz, Arabia",
          ['a.Aliathnayn']),
      locationDeath: at(
          "at.{0} 12 Rabi' al-Awwal 11 AH (8 June 632 CE), Medina, Hejaz, Arabia",
          ['a.Aliathnayn']),
      tomb: null,
      predecessorAr: 'a.Isa',
      successorAr: 'p.None but Mahdi and Isa will follow Islam',
      motherAr: 'a.Amina bint Wahb',
      fatherAr: 'a.Abdullah ibn Abd al-Muttalib',
      spousesAr: null,
      childrenAr: [
        'Al-Qasim (598–601)',
        'Zainab (599–629)',
        'Ruqayyah (601–624)',
        'Umm Kulthum (603–630)',
        'Fatimah (605–632)',
        'Abdullah (611–613)',
        'Ibrahim (630–632)'
      ],
      relativesAr: null,
      kitabAr: 'Quran (42:7)'));
}
